/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package print;

import config.ConexionOracle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class JTable_Proyecto extends javax.swing.JFrame {

    /**
     * Creates new form JTable_Proyecto
     */
    ConexionOracle con1 = new ConexionOracle();
    Connection conet;
    DefaultTableModel modelo = new DefaultTableModel();
    Statement st;
    ResultSet rs;
    int idc;
    int flagBoton = 0;
    int carFlaAct = 0;
    public JTable_Proyecto() {
        initComponents();
        tituloTabla.setText("P1M_PROYECTO");
        setLocationRelativeTo(null);
        ActualizarBoton.setEnabled(false);
        consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloTabla = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtClientCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSecuencia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFecEntregaAño = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTipoProyecto = new javax.swing.JTextField();
        txtFecContratoAño = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFecInicioAño = new javax.swing.JTextField();
        txtFecInicioEfectivoAño = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFecCierreAño = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        txtCostoTotal = new javax.swing.JTextField();
        txtGastos = new javax.swing.JTextField();
        txtUtilidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtMontoTotalReal = new javax.swing.JTextField();
        txtCostoTotalReal = new javax.swing.JTextField();
        txtGastosReal = new javax.swing.JTextField();
        txtUtilidadReal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtFecContratoMes = new javax.swing.JTextField();
        txtFecInicioMes = new javax.swing.JTextField();
        txtFecInicioEfectivoMes = new javax.swing.JTextField();
        txtFecEntregaMes = new javax.swing.JTextField();
        txtFecCierreMes = new javax.swing.JTextField();
        txtFecContratoDia = new javax.swing.JTextField();
        txtFecInicioDia = new javax.swing.JTextField();
        txtFecInicioEfectivoDia = new javax.swing.JTextField();
        txtFecCierreDia = new javax.swing.JTextField();
        txtFecEntregaDia = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtEstadoProyecto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        AgregarBoton = new javax.swing.JButton();
        ModificarBoton = new javax.swing.JButton();
        EliminarBoton = new javax.swing.JButton();
        CancelarBoton = new javax.swing.JButton();
        InactivarBoton = new javax.swing.JButton();
        ReactivarBoton = new javax.swing.JButton();
        ActualizarBoton = new javax.swing.JButton();
        SalirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTabla.setText("Titulo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS"));

        jLabel2.setText("Codigo Cliente");

        txtClientCode.setEditable(false);
        txtClientCode.setEnabled(false);
        txtClientCode.setName(""); // NOI18N

        jLabel3.setText("Secuencia Proyecto");

        txtSecuencia.setEditable(false);
        txtSecuencia.setEnabled(false);

        jLabel4.setText("Fecha de Entrega");

        txtFecEntregaAño.setEditable(false);
        txtFecEntregaAño.setEnabled(false);

        jLabel1.setText("Tipo de Proyecto");

        txtTipoProyecto.setEnabled(false);

        txtFecContratoAño.setEnabled(false);

        jLabel5.setText("Fecha de Contrato");

        jLabel6.setText("Fecha de Inicio");

        jLabel7.setText("Fecha Inicio Efectivo");

        txtFecInicioAño.setEnabled(false);

        txtFecInicioEfectivoAño.setEnabled(false);

        jLabel8.setText("Fecha de Cierre");

        txtFecCierreAño.setEditable(false);
        txtFecCierreAño.setEnabled(false);

        jLabel9.setText("Monto Total");

        jLabel10.setText("Costos");

        jLabel11.setText("Gastos");

        jLabel12.setText("Utilidad");

        txtMontoTotal.setEnabled(false);

        txtCostoTotal.setEnabled(false);

        txtGastos.setEnabled(false);

        txtUtilidad.setEnabled(false);

        jLabel13.setText("Real");

        jLabel14.setText("Real");

        jLabel15.setText("Real");

        jLabel16.setText("Real");

        txtMontoTotalReal.setEnabled(false);

        txtCostoTotalReal.setEnabled(false);

        txtGastosReal.setEnabled(false);

        txtUtilidadReal.setEnabled(false);

        jLabel17.setText("/");

        jLabel18.setText("/");

        jLabel19.setText("/");

        jLabel20.setText("/");

        jLabel21.setText("/");

        jLabel22.setText("/");

        jLabel23.setText("/");

        jLabel24.setText("/");

        jLabel25.setText("/");

        jLabel26.setText("/");

        txtFecContratoMes.setEnabled(false);

        txtFecInicioMes.setEnabled(false);

        txtFecInicioEfectivoMes.setEnabled(false);

        txtFecEntregaMes.setEnabled(false);

        txtFecCierreMes.setEnabled(false);

        txtFecContratoDia.setEnabled(false);

        txtFecInicioDia.setEnabled(false);

        txtFecInicioEfectivoDia.setEnabled(false);

        txtFecCierreDia.setEnabled(false);

        txtFecEntregaDia.setEnabled(false);

        jLabel27.setText("(Año/Mes/Dia)");

        jLabel28.setText("(Año/Mes/Dia)");

        jLabel29.setText("(Año/Mes/Dia)");

        jLabel30.setText("(Año/Mes/Dia)");

        jLabel31.setText("(Año/Mes/Dia)");

        jLabel32.setText("Estado");

        txtEstado.setEnabled(false);

        jLabel33.setText("Estado Proyecto");

        txtEstadoProyecto.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMontoTotalReal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCostoTotalReal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGastosReal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUtilidadReal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel33))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtFecContratoAño, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(txtFecInicioAño, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFecInicioMes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFecContratoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtFecInicioEfectivoAño, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtFecEntregaAño, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtFecCierreAño, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel21)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFecInicioEfectivoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFecEntregaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFecCierreMes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtFecEntregaDia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(txtFecInicioDia, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFecContratoDia, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFecInicioEfectivoDia)
                                        .addComponent(txtFecCierreDia, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel27)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEstadoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel29)
                                        .addComponent(jLabel30)
                                        .addComponent(jLabel31)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(254, 254, 254)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(txtTipoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtClientCode, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecContratoAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecContratoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecContratoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecInicioAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecInicioMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecInicioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecInicioEfectivoAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecInicioEfectivoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecInicioEfectivoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecEntregaAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecEntregaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecEntregaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFecCierreAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFecCierreMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFecCierreDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstadoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoTotalReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtCostoTotalReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtGastosReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtUtilidadReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("BASE DE DATOS"));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Cliente", "Tipo de Proyecto", "Secuencia Proyecto", "Fecha de Contrato", "Fecha de Inicio", "Fecha de Inicio Efectivo", "Fecha de Entrega", "Fecha de Cierre", "Monto Total", "Monto Total Real", "Costos", "Costo Real", "Gastos", "Gasto Real", "Utilidad", "Utilidad Real", "Estado Proyecto", "Estado"
            }
        ));
        jScrollPane2.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("OPCIONES"));

        AgregarBoton.setText("Adicionar");
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });

        ModificarBoton.setText("Modificar");
        ModificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBotonActionPerformed(evt);
            }
        });

        EliminarBoton.setText("Eliminar");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });

        CancelarBoton.setText("Cancelar");
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });

        InactivarBoton.setText("Inactivar");
        InactivarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InactivarBotonActionPerformed(evt);
            }
        });

        ReactivarBoton.setText("Reactivar");
        ReactivarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReactivarBotonActionPerformed(evt);
            }
        });

        ActualizarBoton.setText("Actualizar");
        ActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBotonActionPerformed(evt);
            }
        });

        SalirBoton.setText("Salir");
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModificarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SalirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InactivarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ReactivarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ActualizarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarBoton)
                    .addComponent(ModificarBoton)
                    .addComponent(EliminarBoton)
                    .addComponent(InactivarBoton)
                    .addComponent(ReactivarBoton)
                    .addComponent(ActualizarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalirBoton)
                    .addComponent(CancelarBoton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed
        // get y llamar a adicionar
        flagBoton = 1;
        agregar();
    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void ModificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 2;
        modificar();
    }//GEN-LAST:event_ModificarBotonActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 3;
        eliminar();
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void InactivarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InactivarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 4;
        inactivar();
    }//GEN-LAST:event_InactivarBotonActionPerformed

    private void ReactivarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReactivarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 5;
        reactivar();
    }//GEN-LAST:event_ReactivarBotonActionPerformed

    private void ActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBotonActionPerformed
        actualizar();
    }//GEN-LAST:event_ActualizarBotonActionPerformed

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTable_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTable_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTable_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTable_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTable_Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoton;
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton InactivarBoton;
    private javax.swing.JButton ModificarBoton;
    private javax.swing.JButton ReactivarBoton;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tituloTabla;
    private javax.swing.JTextField txtClientCode;
    private javax.swing.JTextField txtCostoTotal;
    private javax.swing.JTextField txtCostoTotalReal;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstadoProyecto;
    private javax.swing.JTextField txtFecCierreAño;
    private javax.swing.JTextField txtFecCierreDia;
    private javax.swing.JTextField txtFecCierreMes;
    private javax.swing.JTextField txtFecContratoAño;
    private javax.swing.JTextField txtFecContratoDia;
    private javax.swing.JTextField txtFecContratoMes;
    private javax.swing.JTextField txtFecEntregaAño;
    private javax.swing.JTextField txtFecEntregaDia;
    private javax.swing.JTextField txtFecEntregaMes;
    private javax.swing.JTextField txtFecInicioAño;
    private javax.swing.JTextField txtFecInicioDia;
    private javax.swing.JTextField txtFecInicioEfectivoAño;
    private javax.swing.JTextField txtFecInicioEfectivoDia;
    private javax.swing.JTextField txtFecInicioEfectivoMes;
    private javax.swing.JTextField txtFecInicioMes;
    private javax.swing.JTextField txtGastos;
    private javax.swing.JTextField txtGastosReal;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtMontoTotalReal;
    private javax.swing.JTextField txtSecuencia;
    private javax.swing.JTextField txtTipoProyecto;
    private javax.swing.JTextField txtUtilidad;
    private javax.swing.JTextField txtUtilidadReal;
    // End of variables declaration//GEN-END:variables
    
    private final String NOMBRE_TABLA = "p1m_proyecto";
    private final String NOMBRE_INSTACIA = "Proyecto";
    private final int CANTIDAD_DATOS = 28;
    
    private final String NOMBRE_DATO_1 = "ProCliCod";
    private final String NOMBRE_DATO_2 = "ProTipProCod";
    private final String NOMBRE_DATO_3 = "ProSecPro";
    
    private final String NOMBRE_DATO_4 = "ProFecProConAño";
    private final String NOMBRE_DATO_5 = "ProFecProConMes";
    private final String NOMBRE_DATO_6 = "ProFecProConDia";
    
    private final String NOMBRE_DATO_7 = "ProFecProPacAño";
    private final String NOMBRE_DATO_8 = "ProFecProPacMes";
    private final String NOMBRE_DATO_9 = "ProFecProPacDia";
    
    private final String NOMBRE_DATO_10 = "ProFecProIniAño";
    private final String NOMBRE_DATO_11 = "ProFecProIniMes";
    private final String NOMBRE_DATO_12 = "ProFecProIniDia";
    
    private final String NOMBRE_DATO_13 = "ProFecProEntAño";
    private final String NOMBRE_DATO_14 = "ProFecProEntMes";
    private final String NOMBRE_DATO_15 = "ProFecProEntDia";
    
    private final String NOMBRE_DATO_16 = "ProFecProCieAño";
    private final String NOMBRE_DATO_17 = "ProFecProCieMes";
    private final String NOMBRE_DATO_18 = "ProFecProCieDia";
    
    private final String NOMBRE_DATO_19 = "ProMonPro";
    private final String NOMBRE_DATO_20 = "ProMonProRea";
    
    private final String NOMBRE_DATO_21 = "ProMonProCos";
    private final String NOMBRE_DATO_22 = "ProMonProCosRea";
    
    private final String NOMBRE_DATO_23 = "ProMonProGas";
    private final String NOMBRE_DATO_24 = "ProMonProGasRea";
    
    private final String NOMBRE_DATO_25 = "ProMonProUti";
    private final String NOMBRE_DATO_26 = "ProMonProUtiRea";
    
    private final String NOMBRE_DATO_27 = "ProEstPro";
    private final String NOMBRE_DATO_28 = "ProEstReg";
    
    private void consulta() {
        String sql = "select * from " + NOMBRE_TABLA + " order by " + NOMBRE_DATO_1;

        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] tipoClientes = new Object[18];
            modelo = (DefaultTableModel) Tabla.getModel();
            
            //INGRESE NOMBRES DATOS TABLA
            while (rs.next()) { 
                tipoClientes[0] = rs.getInt(NOMBRE_DATO_1);
                tipoClientes[1] = rs.getInt(NOMBRE_DATO_2);
                tipoClientes[2] = rs.getInt(NOMBRE_DATO_3);
                tipoClientes[3] = rs.getInt(NOMBRE_DATO_4)+"/"+rs.getInt(NOMBRE_DATO_5)+"/"+rs.getInt(NOMBRE_DATO_6);
                tipoClientes[4] = rs.getInt(NOMBRE_DATO_7)+"/"+rs.getInt(NOMBRE_DATO_8)+"/"+rs.getInt(NOMBRE_DATO_9);
                tipoClientes[5] = rs.getInt(NOMBRE_DATO_10)+"/"+rs.getInt(NOMBRE_DATO_11)+"/"+rs.getInt(NOMBRE_DATO_12);
                tipoClientes[6] = rs.getInt(NOMBRE_DATO_13)+"/"+rs.getInt(NOMBRE_DATO_14)+"/"+rs.getInt(NOMBRE_DATO_15);
                tipoClientes[7] = rs.getInt(NOMBRE_DATO_16)+"/"+rs.getInt(NOMBRE_DATO_17)+"/"+rs.getInt(NOMBRE_DATO_18);
                tipoClientes[8] = rs.getInt(NOMBRE_DATO_19);
                tipoClientes[9] = rs.getInt(NOMBRE_DATO_20);
                tipoClientes[10] = rs.getInt(NOMBRE_DATO_21);
                tipoClientes[11] = rs.getInt(NOMBRE_DATO_22);
                tipoClientes[12] = rs.getInt(NOMBRE_DATO_23);
                tipoClientes[13] = rs.getInt(NOMBRE_DATO_24);
                tipoClientes[14] = rs.getInt(NOMBRE_DATO_25);
                tipoClientes[15] = rs.getInt(NOMBRE_DATO_26);
                tipoClientes[16] = rs.getInt(NOMBRE_DATO_27);
                tipoClientes[17] = rs.getString(NOMBRE_DATO_28);
                
                modelo.addRow(tipoClientes);
            }
            Tabla.setModel(modelo);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void agregar() {
        ActualizarBoton.setEnabled(true);
        
        //init not default values
        setFormEdit(true);
        setFormEnab(true);
        
        //default values
        txtEstado.setEditable(false);
        txtEstado.setEnabled(false);
        txtEstado.setText("A");
        
        carFlaAct = 1;
    }

    private void actualizar() {
        String codigo = txtClientCode.getText();
        String tipoProyecto = txtTipoProyecto.getText();
        String secuencia = txtSecuencia.getText();
        
        String fContA = txtFecContratoAño.getText();
        String fContM = txtFecContratoMes.getText();
        String fContD = txtFecContratoDia.getText();
        String fIniA = txtFecInicioAño.getText();
        String fIniM = txtFecInicioMes.getText();
        String fIniD = txtFecInicioDia.getText();
        String fIniEfeA = txtFecInicioEfectivoAño.getText();
        String fIniEfeM = txtFecInicioEfectivoMes.getText();
        String fIniEfeD = txtFecInicioEfectivoDia.getText();
        String fEntA = txtFecEntregaAño.getText();
        String fEntM = txtFecEntregaMes.getText();
        String fEntD = txtFecEntregaDia.getText();
        String fCieA = txtFecCierreAño.getText();
        String fCieM = txtFecCierreMes.getText();
        String fCieD = txtFecCierreDia.getText();
        
        String monto = txtMontoTotal.getText();
        String montoReal = txtMontoTotalReal.getText();
        String costo = txtCostoTotal.getText();
        String costoReal = txtCostoTotalReal.getText();
        String gasto = txtGastos.getText();
        String gastoReal = txtGastosReal.getText();
        String utilidad = txtUtilidad.getText();
        String utilidadReal = txtUtilidadReal.getText();
        String estadoProyecto = txtEstadoProyecto.getText();
        String estado = txtEstado.getText();
        
        switch (flagBoton) {
            case 1:
                //AgregarBoton.setEnabled(false);
                if ((codigo.equals("")) || (tipoProyecto.equals("")) || (secuencia.equals("")) || (fContA.equals("")) || (fContM.equals(""))
                  || (fContD.equals("")) || (fIniA.equals("")) || (fIniM.equals("")) || (fIniD.equals("")) || (fIniEfeA.equals(""))
                  || (fIniEfeM.equals("")) || (fIniEfeD.equals("")) || (fEntA.equals("")) || (fEntM.equals("")) || (fEntD.equals(""))
                  || (fCieA.equals("")) || (fCieM.equals("")) || (fCieD.equals("")) || (monto.equals("")) || (montoReal.equals(""))
                  || (costo.equals("")) || (costoReal.equals("")) || (gasto.equals("")) || (gastoReal.equals("")) || (utilidad.equals(""))
                  || (utilidadReal.equals("")) || (estadoProyecto.equals("")) ) {
                    JOptionPane.showMessageDialog(null, "Falta Ingresar Datos!");
                } else {
                    if ((carFlaAct == 1)) {
                        try {
                            String sql = "insert into "+NOMBRE_TABLA+" ("+NOMBRE_DATO_1+", "+NOMBRE_DATO_2+", "+NOMBRE_DATO_3+", "
                                                      +NOMBRE_DATO_4+", "+NOMBRE_DATO_5+", "+NOMBRE_DATO_6+", "+NOMBRE_DATO_7+", "
                                                      +NOMBRE_DATO_8+", "+NOMBRE_DATO_9+", "+NOMBRE_DATO_10+", "+NOMBRE_DATO_11+", "
                                                      +NOMBRE_DATO_12+", "+NOMBRE_DATO_13+", "+NOMBRE_DATO_14+", "+NOMBRE_DATO_15+", "
                                                      +NOMBRE_DATO_16+", "+NOMBRE_DATO_17+", "+NOMBRE_DATO_18+", "+NOMBRE_DATO_19+", "
                                                      +NOMBRE_DATO_20+", "+NOMBRE_DATO_21+", "+NOMBRE_DATO_22+", "+NOMBRE_DATO_23+", "
                                                      +NOMBRE_DATO_24+", "+NOMBRE_DATO_25+", "+NOMBRE_DATO_26+", "+NOMBRE_DATO_27+", "
                                                      +NOMBRE_DATO_28+")"
                                                        + " values('" + codigo + "','" + tipoProyecto + "','" + secuencia + "','"
                                                        + fContA + "','" + fContM + "','" + fContD + "','" + fIniA + "','" 
                                                        + fIniM + "','" + fIniD + "','" + fIniEfeA + "','" + fIniEfeM + "','" 
                                                        + fIniEfeD + "','" + fEntA + "','" + fEntM + "','" + fEntD + "','" 
                                                        + fCieA + "','" + fCieM + "','" + fCieD + "','" + monto + "','" 
                                                        + montoReal + "','" + costo + "','" + costoReal + "','" + gasto + "','" 
                                                        + gastoReal + "','" + utilidad + "','" + utilidadReal + "','" + estadoProyecto + "','" 
                                                        + estado + "')";
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            System.out.println(sql);
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, "Nuevo "+NOMBRE_INSTACIA+" Registrado!");
                            limpiarFormulario();
                            desactivarFormularioEdic();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e.getMessage());
                            consulta();
                        }
                    } else {
                        System.out.println("Flag Error");
                    }
                }
                break;
            case 2:
                //ModificarBoton.setEnabled(false);
                if ((codigo.equals("")) || (tipoProyecto.equals("")) || (secuencia.equals("")) || (fContA.equals("")) || (fContM.equals(""))
                  || (fContD.equals("")) || (fIniA.equals("")) || (fIniM.equals("")) || (fIniD.equals("")) || (fIniEfeA.equals(""))
                  || (fIniEfeM.equals("")) || (fIniEfeD.equals("")) || (fEntA.equals("")) || (fEntM.equals("")) || (fEntD.equals(""))
                  || (fCieA.equals("")) || (fCieM.equals("")) || (fCieD.equals("")) || (monto.equals("")) || (montoReal.equals(""))
                  || (costo.equals("")) || (costoReal.equals("")) || (gasto.equals("")) || (gastoReal.equals("")) || (utilidad.equals(""))
                  || (utilidadReal.equals("")) || (estadoProyecto.equals(""))) {
                    JOptionPane.showMessageDialog(null, "Falta Ingresar Datos!");
                } else {
                    if ((carFlaAct == 1)) {
                        try {
                            String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_1+"='" + codigo +"', "+ NOMBRE_DATO_2+"='" + tipoProyecto +"', "+ NOMBRE_DATO_3+"='" + secuencia +"', "
                                                                       +NOMBRE_DATO_4+"='" + fContA +"', " +NOMBRE_DATO_5+"='" + fContM +"', "
                                                                       +NOMBRE_DATO_6+"='" + fContD +"', " +NOMBRE_DATO_7+"='" + fIniA +"', "
                                                                       +NOMBRE_DATO_8+"='" + fIniM +"', " +NOMBRE_DATO_9+"='" + fIniD +"', "
                                                                       +NOMBRE_DATO_10+"='" + fIniEfeA +"', " +NOMBRE_DATO_11+"='" + fIniEfeM +"', "
                                                                       +NOMBRE_DATO_12+"='" + fIniEfeD +"', " +NOMBRE_DATO_13+"='" + fEntA +"', "
                                                                       +NOMBRE_DATO_14+"='" + fEntM +"', " +NOMBRE_DATO_15+"='" + fEntD +"', "
                                                                       +NOMBRE_DATO_16+"='" + fCieA +"', " +NOMBRE_DATO_17+"='" + fCieM +"', "
                                                                       +NOMBRE_DATO_18+"='" + fCieD +"', " +NOMBRE_DATO_19+"='" + monto +"', "
                                                                       +NOMBRE_DATO_20+"='" + montoReal +"', " +NOMBRE_DATO_21+"='" + costo +"', "
                                                                       +NOMBRE_DATO_22+"='" + costoReal +"', " +NOMBRE_DATO_23+"='" + gasto +"', "
                                                                       +NOMBRE_DATO_24+"='" + gastoReal +"', " +NOMBRE_DATO_25+"='" + utilidad +"', "
                                                                       +NOMBRE_DATO_26+"='" + utilidadReal +"', " +NOMBRE_DATO_27+"='" + estadoProyecto
                                                                       + "' where ("+NOMBRE_DATO_1+"='" + codigo +"' AND "+NOMBRE_DATO_2+"='" + tipoProyecto
                                                                                     +"' AND "+NOMBRE_DATO_3+"='" + secuencia + "')";
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Actualizado!");
                            limpiarFormulario();
                            desactivarFormularioEdic();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e.getMessage());
                            consulta();
                        }
                    } else {
                        System.out.println("Flag Error");
                    }
                }
                break;
            case 3:
                //EliminarBoton.setEnabled(false);
                if (carFlaAct == 1) {
                    try {
                        String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_28+"='*' where ("+NOMBRE_DATO_1+"='" + codigo +"' AND "+NOMBRE_DATO_2+"='" + tipoProyecto
                                                                                     +"' AND "+NOMBRE_DATO_3+"='" + secuencia + "')";
                        conet = con1.getConnection();
                        st = conet.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Eliminado!");
                        limpiarFormulario();
                        desactivarFormularioEdic();
                        limpiarTabla();
                    } catch (Exception e) {
                        System.out.println("Error SQL: " + e.getMessage());
                        consulta();
                    }
                }
                break;
            case 4:
                //InactivarBoton.setEnabled(false);
                if (carFlaAct == 1) {
                    try {
                        String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_28+"='I' where ("+NOMBRE_DATO_1+"='" + codigo +"' AND "+NOMBRE_DATO_2+"='" + tipoProyecto
                                                                                     +"' AND "+NOMBRE_DATO_3+"='" + secuencia + "')";
                        conet = con1.getConnection();
                        st = conet.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Inactivado!");
                        limpiarFormulario();
                        desactivarFormularioEdic();
                        limpiarTabla();
                    } catch (Exception e) {
                        System.out.println("Error SQL: " + e.getMessage());
                        consulta();
                    }
                }
                break;
            case 5:
                //ReactivarBoton.setEnabled(false);
                if (estado.equals("*") || estado.equals("I")) {
                    if (carFlaAct == 1) {
                        try {
                            String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_28+"='A' where ("+NOMBRE_DATO_1+"='" + codigo +"' AND "+NOMBRE_DATO_2+"='" + tipoProyecto
                                                                                     +"' AND "+NOMBRE_DATO_3+"='" + secuencia + "')";
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Reactivado!");
                            limpiarFormulario();
                            desactivarFormularioEdic();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e.getMessage());
                            consulta();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El estado se encuentra activo");
                }
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se realizo ninguna modificacion");
                break;
        }
        flagBoton = 0;
        
    }

    private void cancelar() {
        carFlaAct = 0;
        limpiarFormulario();
        desactivarFormularioEdic();
        ActualizarBoton.setEnabled(false);
    }

    private void limpiarTabla() {
        for (int i = 0; i <= Tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    private void limpiarFormulario() {
        String t = "";
        txtClientCode.setText(t);
        txtTipoProyecto.setText(t);
        txtSecuencia.setText(t);
        
        txtFecContratoAño.setText(t);
        txtFecContratoMes.setText(t);
        txtFecContratoDia.setText(t);
        txtFecInicioAño.setText(t);
        txtFecInicioMes.setText(t);
        txtFecInicioDia.setText(t);
        txtFecInicioEfectivoAño.setText(t);
        txtFecInicioEfectivoMes.setText(t);
        txtFecInicioEfectivoDia.setText(t);
        txtFecEntregaAño.setText(t);
        txtFecEntregaMes.setText(t);
        txtFecEntregaDia.setText(t);
        txtFecCierreAño.setText(t);
        txtFecCierreMes.setText(t);
        txtFecCierreDia.setText(t);
        
        txtMontoTotal.setText(t);
        txtMontoTotalReal.setText(t);
        txtCostoTotal.setText(t);
        txtCostoTotalReal.setText(t);
        txtGastos.setText(t);
        txtGastosReal.setText(t);
        txtUtilidad.setText(t);
        txtUtilidadReal.setText(t);
        txtEstadoProyecto.setText(t);
        txtEstado.setText(t);
    }
    
    private void rellenarFormulario(String c, String tp, String s, String ca, String cm, String cd,
                                    String ia, String im, String id, String iea, String iem, String ied,
                                    String ea, String em, String ed, String cia, String cim, String cid,
                                    String mt, String mtr, String ct, String ctr, String gt, String gtr,
                                    String ut, String utr, String ep, String e) {
        txtClientCode.setText(c);
        txtTipoProyecto.setText(tp);
        txtSecuencia.setText(s);
        
        txtFecContratoAño.setText(ca);
        txtFecContratoMes.setText(cm);
        txtFecContratoDia.setText(cd);
        txtFecInicioAño.setText(ia);
        txtFecInicioMes.setText(im);
        txtFecInicioDia.setText(id);
        txtFecInicioEfectivoAño.setText(iea);
        txtFecInicioEfectivoMes.setText(iem);
        txtFecInicioEfectivoDia.setText(ied);
        txtFecEntregaAño.setText(ea);
        txtFecEntregaMes.setText(em);
        txtFecEntregaDia.setText(ed);
        txtFecCierreAño.setText(cia);
        txtFecCierreMes.setText(cim);
        txtFecCierreDia.setText(cid);
        
        txtMontoTotal.setText(mt);
        txtMontoTotalReal.setText(mtr);
        txtCostoTotal.setText(ct);
        txtCostoTotalReal.setText(ctr);
        txtGastos.setText(gt);
        txtGastosReal.setText(gtr);
        txtUtilidad.setText(ut);
        txtUtilidadReal.setText(utr);
        txtEstadoProyecto.setText(ep);
        txtEstado.setText(e);
    }
    
    private void setFormEdit(boolean t){
        txtClientCode.setEditable(t);
        txtTipoProyecto.setEditable(t);
        txtSecuencia.setEditable(t);
        
        txtFecContratoAño.setEditable(t);
        txtFecContratoMes.setEditable(t);
        txtFecContratoDia.setEditable(t);
        txtFecInicioAño.setEditable(t);
        txtFecInicioMes.setEditable(t);
        txtFecInicioDia.setEditable(t);
        txtFecInicioEfectivoAño.setEditable(t);
        txtFecInicioEfectivoMes.setEditable(t);
        txtFecInicioEfectivoDia.setEditable(t);
        txtFecEntregaAño.setEditable(t);
        txtFecEntregaMes.setEditable(t);
        txtFecEntregaDia.setEditable(t);
        txtFecCierreAño.setEditable(t);
        txtFecCierreMes.setEditable(t);
        txtFecCierreDia.setEditable(t);
        
        txtMontoTotal.setEditable(t);
        txtMontoTotalReal.setEditable(t);
        txtCostoTotal.setEditable(t);
        txtCostoTotalReal.setEditable(t);
        txtGastos.setEditable(t);
        txtGastosReal.setEditable(t);
        txtUtilidad.setEditable(t);
        txtUtilidadReal.setEditable(t);
        txtEstadoProyecto.setEditable(t);
        txtEstado.setEditable(t);
    }
    
    private void setFormEnab(boolean t){
        txtClientCode.setEnabled(t);
        txtTipoProyecto.setEnabled(t);
        txtSecuencia.setEnabled(t);
        
        txtFecContratoAño.setEnabled(t);
        txtFecContratoMes.setEnabled(t);
        txtFecContratoDia.setEnabled(t);
        txtFecInicioAño.setEnabled(t);
        txtFecInicioMes.setEnabled(t);
        txtFecInicioDia.setEnabled(t);
        txtFecInicioEfectivoAño.setEnabled(t);
        txtFecInicioEfectivoMes.setEnabled(t);
        txtFecInicioEfectivoDia.setEnabled(t);
        txtFecEntregaAño.setEnabled(t);
        txtFecEntregaMes.setEnabled(t);
        txtFecEntregaDia.setEnabled(t);
        txtFecCierreAño.setEnabled(t);
        txtFecCierreMes.setEnabled(t);
        txtFecCierreDia.setEnabled(t);
        
        txtMontoTotal.setEnabled(t);
        txtMontoTotalReal.setEnabled(t);
        txtCostoTotal.setEnabled(t);
        txtCostoTotalReal.setEnabled(t);
        txtGastos.setEnabled(t);
        txtGastosReal.setEnabled(t);
        txtUtilidad.setEnabled(t);
        txtUtilidadReal.setEnabled(t);
        txtEstadoProyecto.setEnabled(t);
        txtEstado.setEnabled(t);
    }
    
    private void desactivarFormularioEdic() {
        setFormEdit(false);
        desactivarFormularioEnab();
    }
    
    private void desactivarFormularioEnab() {
        setFormEnab(false);
    }
    
    private void activarFormulario() {
        setFormEdit(true);
        setFormEnab(true);
    }

    private void eliminar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            String codigo = (String) Tabla.getValueAt(fila, 0).toString();
            String tipoProyecto = (String) Tabla.getValueAt(fila, 1).toString();
            String secuencia = (String) Tabla.getValueAt(fila, 2).toString();

            String fCont = (String) Tabla.getValueAt(fila, 3).toString();
            String fIni = (String) Tabla.getValueAt(fila, 4).toString();
            String fIniEfe = (String) Tabla.getValueAt(fila, 5).toString();
            String fEnt = (String) Tabla.getValueAt(fila, 6).toString();
            String fCie = (String) Tabla.getValueAt(fila, 7).toString();

            String monto = (String) Tabla.getValueAt(fila, 8).toString();
            String montoReal = (String) Tabla.getValueAt(fila, 9).toString();
            String costo = (String) Tabla.getValueAt(fila, 10).toString();
            String costoReal = (String) Tabla.getValueAt(fila, 11).toString();
            String gasto = (String) Tabla.getValueAt(fila, 12).toString();
            String gastoReal = (String) Tabla.getValueAt(fila, 13).toString();
            String utilidad = (String) Tabla.getValueAt(fila, 14).toString();
            String utilidadReal = (String) Tabla.getValueAt(fila, 15).toString();
            String estadoProyecto = (String) Tabla.getValueAt(fila, 16).toString();
            String estado = (String) Tabla.getValueAt(fila, 17).toString();
            
            String fContA = fCont.substring(0, fCont.indexOf("/"));
            String fContM = fCont.substring(fCont.indexOf("/")+1, fCont.lastIndexOf("/"));
            String fContD = fCont.substring(fCont.lastIndexOf("/")+1, fCont.length());
            String fIniA = fIni.substring(0, fIni.indexOf("/"));
            String fIniM = fIni.substring(fIni.indexOf("/")+1, fIni.lastIndexOf("/"));
            String fIniD = fIni.substring(fIni.lastIndexOf("/")+1, fIni.length());
            String fIniEfeA = fIniEfe.substring(0, fIniEfe.indexOf("/"));
            String fIniEfeM = fIniEfe.substring(fIniEfe.indexOf("/")+1, fIniEfe.lastIndexOf("/"));
            String fIniEfeD = fIniEfe.substring(fIniEfe.lastIndexOf("/")+1, fIniEfe.length());
            String fEntA = fEnt.substring(0, fEnt.indexOf("/"));
            String fEntM = fEnt.substring(fEnt.indexOf("/")+1, fEnt.lastIndexOf("/"));
            String fEntD = fEnt.substring(fEnt.lastIndexOf("/")+1, fEnt.length());
            String fCieA = fCie.substring(0, fCie.indexOf("/"));
            String fCieM = fCie.substring(fCie.indexOf("/")+1, fCie.lastIndexOf("/"));
            String fCieD = fCie.substring(fCie.lastIndexOf("/")+1, fCie.length());
            
            rellenarFormulario(codigo, tipoProyecto, secuencia, fContA, fContM, fContD, fIniA, fIniM, fIniD, fIniEfeA, fIniEfeM,
                               fIniEfeD, fEntA, fEntM, fEntD, fCieA, fCieM, fCieD, monto, montoReal, costo, costoReal, gasto,
                               gastoReal, utilidad, utilidadReal, estadoProyecto, estado);
            
            desactivarFormularioEdic();
            carFlaAct = 1;

            //String sql = "select * from c1z_tipo_clientes";
        }
    }

    private void modificar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            String codigo = (String) Tabla.getValueAt(fila, 0).toString();
            String tipoProyecto = (String) Tabla.getValueAt(fila, 1).toString();
            String secuencia = (String) Tabla.getValueAt(fila, 2).toString();

            String fCont = (String) Tabla.getValueAt(fila, 3).toString();
            String fIni = (String) Tabla.getValueAt(fila, 4).toString();
            String fIniEfe = (String) Tabla.getValueAt(fila, 5).toString();
            String fEnt = (String) Tabla.getValueAt(fila, 6).toString();
            String fCie = (String) Tabla.getValueAt(fila, 7).toString();

            String monto = (String) Tabla.getValueAt(fila, 8).toString();
            String montoReal = (String) Tabla.getValueAt(fila, 9).toString();
            String costo = (String) Tabla.getValueAt(fila, 10).toString();
            String costoReal = (String) Tabla.getValueAt(fila, 11).toString();
            String gasto = (String) Tabla.getValueAt(fila, 12).toString();
            String gastoReal = (String) Tabla.getValueAt(fila, 13).toString();
            String utilidad = (String) Tabla.getValueAt(fila, 14).toString();
            String utilidadReal = (String) Tabla.getValueAt(fila, 15).toString();
            String estadoProyecto = (String) Tabla.getValueAt(fila, 16).toString();
            String estado = (String) Tabla.getValueAt(fila, 17).toString();
            
            String fContA = fCont.substring(0, fCont.indexOf("/"));
            String fContM = fCont.substring(fCont.indexOf("/")+1, fCont.lastIndexOf("/"));
            String fContD = fCont.substring(fCont.lastIndexOf("/")+1, fCont.length());
            String fIniA = fIni.substring(0, fIni.indexOf("/"));
            String fIniM = fIni.substring(fIni.indexOf("/")+1, fIni.lastIndexOf("/"));
            String fIniD = fIni.substring(fIni.lastIndexOf("/")+1, fIni.length());
            String fIniEfeA = fIniEfe.substring(0, fIniEfe.indexOf("/"));
            String fIniEfeM = fIniEfe.substring(fIniEfe.indexOf("/")+1, fIniEfe.lastIndexOf("/"));
            String fIniEfeD = fIniEfe.substring(fIniEfe.lastIndexOf("/")+1, fIniEfe.length());
            String fEntA = fEnt.substring(0, fEnt.indexOf("/"));
            String fEntM = fEnt.substring(fEnt.indexOf("/")+1, fEnt.lastIndexOf("/"));
            String fEntD = fEnt.substring(fEnt.lastIndexOf("/")+1, fEnt.length());
            String fCieA = fCie.substring(0, fCie.indexOf("/"));
            String fCieM = fCie.substring(fCie.indexOf("/")+1, fCie.lastIndexOf("/"));
            String fCieD = fCie.substring(fCie.lastIndexOf("/")+1, fCie.length());
            
            rellenarFormulario(codigo, tipoProyecto, secuencia, fContA, fContM, fContD, fIniA, fIniM, fIniD, fIniEfeA, fIniEfeM,
                               fIniEfeD, fEntA, fEntM, fEntD, fCieA, fCieM, fCieD, monto, montoReal, costo, costoReal, gasto,
                               gastoReal, utilidad, utilidadReal, estadoProyecto, estado);
            activarFormulario();
            txtEstado.setEditable(false);
            txtEstado.setEnabled(false);
            
            carFlaAct = 1;
        }
    }

    private void inactivar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            String codigo = (String) Tabla.getValueAt(fila, 0).toString();
            String tipoProyecto = (String) Tabla.getValueAt(fila, 1).toString();
            String secuencia = (String) Tabla.getValueAt(fila, 2).toString();

            String fCont = (String) Tabla.getValueAt(fila, 3).toString();
            String fIni = (String) Tabla.getValueAt(fila, 4).toString();
            String fIniEfe = (String) Tabla.getValueAt(fila, 5).toString();
            String fEnt = (String) Tabla.getValueAt(fila, 6).toString();
            String fCie = (String) Tabla.getValueAt(fila, 7).toString();

            String monto = (String) Tabla.getValueAt(fila, 8).toString();
            String montoReal = (String) Tabla.getValueAt(fila, 9).toString();
            String costo = (String) Tabla.getValueAt(fila, 10).toString();
            String costoReal = (String) Tabla.getValueAt(fila, 11).toString();
            String gasto = (String) Tabla.getValueAt(fila, 12).toString();
            String gastoReal = (String) Tabla.getValueAt(fila, 13).toString();
            String utilidad = (String) Tabla.getValueAt(fila, 14).toString();
            String utilidadReal = (String) Tabla.getValueAt(fila, 15).toString();
            String estadoProyecto = (String) Tabla.getValueAt(fila, 16).toString();
            String estado = (String) Tabla.getValueAt(fila, 17).toString();
            
            String fContA = fCont.substring(0, fCont.indexOf("/"));
            String fContM = fCont.substring(fCont.indexOf("/")+1, fCont.lastIndexOf("/"));
            String fContD = fCont.substring(fCont.lastIndexOf("/")+1, fCont.length());
            String fIniA = fIni.substring(0, fIni.indexOf("/"));
            String fIniM = fIni.substring(fIni.indexOf("/")+1, fIni.lastIndexOf("/"));
            String fIniD = fIni.substring(fIni.lastIndexOf("/")+1, fIni.length());
            String fIniEfeA = fIniEfe.substring(0, fIniEfe.indexOf("/"));
            String fIniEfeM = fIniEfe.substring(fIniEfe.indexOf("/")+1, fIniEfe.lastIndexOf("/"));
            String fIniEfeD = fIniEfe.substring(fIniEfe.lastIndexOf("/")+1, fIniEfe.length());
            String fEntA = fEnt.substring(0, fEnt.indexOf("/"));
            String fEntM = fEnt.substring(fEnt.indexOf("/")+1, fEnt.lastIndexOf("/"));
            String fEntD = fEnt.substring(fEnt.lastIndexOf("/")+1, fEnt.length());
            String fCieA = fCie.substring(0, fCie.indexOf("/"));
            String fCieM = fCie.substring(fCie.indexOf("/")+1, fCie.lastIndexOf("/"));
            String fCieD = fCie.substring(fCie.lastIndexOf("/")+1, fCie.length());
            
            rellenarFormulario(codigo, tipoProyecto, secuencia, fContA, fContM, fContD, fIniA, fIniM, fIniD, fIniEfeA, fIniEfeM,
                               fIniEfeD, fEntA, fEntM, fEntD, fCieA, fCieM, fCieD, monto, montoReal, costo, costoReal, gasto,
                               gastoReal, utilidad, utilidadReal, estadoProyecto, estado);
            desactivarFormularioEdic();
            carFlaAct = 1;

        }
    }

    private void reactivar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            String codigo = (String) Tabla.getValueAt(fila, 0).toString();
            String tipoProyecto = (String) Tabla.getValueAt(fila, 1).toString();
            String secuencia = (String) Tabla.getValueAt(fila, 2).toString();

            String fCont = (String) Tabla.getValueAt(fila, 3).toString();
            String fIni = (String) Tabla.getValueAt(fila, 4).toString();
            String fIniEfe = (String) Tabla.getValueAt(fila, 5).toString();
            String fEnt = (String) Tabla.getValueAt(fila, 6).toString();
            String fCie = (String) Tabla.getValueAt(fila, 7).toString();

            String monto = (String) Tabla.getValueAt(fila, 8).toString();
            String montoReal = (String) Tabla.getValueAt(fila, 9).toString();
            String costo = (String) Tabla.getValueAt(fila, 10).toString();
            String costoReal = (String) Tabla.getValueAt(fila, 11).toString();
            String gasto = (String) Tabla.getValueAt(fila, 12).toString();
            String gastoReal = (String) Tabla.getValueAt(fila, 13).toString();
            String utilidad = (String) Tabla.getValueAt(fila, 14).toString();
            String utilidadReal = (String) Tabla.getValueAt(fila, 15).toString();
            String estadoProyecto = (String) Tabla.getValueAt(fila, 16).toString();
            String estado = (String) Tabla.getValueAt(fila, 17).toString();
            
            String fContA = fCont.substring(0, fCont.indexOf("/"));
            String fContM = fCont.substring(fCont.indexOf("/")+1, fCont.lastIndexOf("/"));
            String fContD = fCont.substring(fCont.lastIndexOf("/")+1, fCont.length());
            String fIniA = fIni.substring(0, fIni.indexOf("/"));
            String fIniM = fIni.substring(fIni.indexOf("/")+1, fIni.lastIndexOf("/"));
            String fIniD = fIni.substring(fIni.lastIndexOf("/")+1, fIni.length());
            String fIniEfeA = fIniEfe.substring(0, fIniEfe.indexOf("/"));
            String fIniEfeM = fIniEfe.substring(fIniEfe.indexOf("/")+1, fIniEfe.lastIndexOf("/"));
            String fIniEfeD = fIniEfe.substring(fIniEfe.lastIndexOf("/")+1, fIniEfe.length());
            String fEntA = fEnt.substring(0, fEnt.indexOf("/"));
            String fEntM = fEnt.substring(fEnt.indexOf("/")+1, fEnt.lastIndexOf("/"));
            String fEntD = fEnt.substring(fEnt.lastIndexOf("/")+1, fEnt.length());
            String fCieA = fCie.substring(0, fCie.indexOf("/"));
            String fCieM = fCie.substring(fCie.indexOf("/")+1, fCie.lastIndexOf("/"));
            String fCieD = fCie.substring(fCie.lastIndexOf("/")+1, fCie.length());
            
            rellenarFormulario(codigo, tipoProyecto, secuencia, fContA, fContM, fContD, fIniA, fIniM, fIniD, fIniEfeA, fIniEfeM,
                               fIniEfeD, fEntA, fEntM, fEntD, fCieA, fCieM, fCieD, monto, montoReal, costo, costoReal, gasto,
                               gastoReal, utilidad, utilidadReal, estadoProyecto, estado);
            desactivarFormularioEdic();
            carFlaAct = 1;
        }
    }
}
