/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package print;

import config.ConexionOracle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel Hincho
 */
public class JTable_Clientes extends javax.swing.JFrame {

    ConexionOracle con1 = new ConexionOracle();
    Connection conet;
    DefaultTableModel modelo = new DefaultTableModel();
    Statement st;
    ResultSet rs;
    int idc;
    int flagBoton = 0;
    int carFlaAct = 0;

    public JTable_Clientes() {
        initComponents();
        tituloTabla.setText("C13002 - CONTROL DE CLIENTES");
        setLocationRelativeTo(null);
        ActualizarBoton.setEnabled(false);
        consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CliCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CliNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CliEstReg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CliFecIngDia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CliTipCli = new javax.swing.JTextField();
        CliFecIngMes = new javax.swing.JTextField();
        CliFecIngAnio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CliFecCesDia = new javax.swing.JTextField();
        CliFecCesMes = new javax.swing.JTextField();
        CliFecCesAnio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CliFecUltDia = new javax.swing.JTextField();
        CliFecUltMes = new javax.swing.JTextField();
        CliFecUltAnio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CliEstCli = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        AgregarBoton = new javax.swing.JButton();
        ModificarBoton = new javax.swing.JButton();
        EliminarBoton = new javax.swing.JButton();
        CancelarBoton = new javax.swing.JButton();
        InactivarBoton = new javax.swing.JButton();
        ReactivarBoton = new javax.swing.JButton();
        ActualizarBoton = new javax.swing.JButton();
        SalirBoton = new javax.swing.JButton();
        tituloTabla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS"));

        jLabel2.setText("Codigo");

        CliCod.setEditable(false);
        CliCod.setName(""); // NOI18N

        jLabel3.setText("Nombre");

        CliNom.setEditable(false);
        CliNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliNomActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado Registro");

        CliEstReg.setEditable(false);
        CliEstReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliEstRegActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo Cliente");

        CliFecIngDia.setEditable(false);
        CliFecIngDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliFecIngDiaActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha Ingreso");

        CliTipCli.setEditable(false);
        CliTipCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliTipCliActionPerformed(evt);
            }
        });

        CliFecIngMes.setEditable(false);
        CliFecIngMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliFecIngMesActionPerformed(evt);
            }
        });

        CliFecIngAnio.setEditable(false);
        CliFecIngAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliFecIngAnioActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha Ceso");

        CliFecCesDia.setEditable(false);
        CliFecCesDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliFecCesDiaActionPerformed(evt);
            }
        });

        CliFecCesMes.setEditable(false);
        CliFecCesMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliFecCesMesActionPerformed(evt);
            }
        });

        CliFecCesAnio.setEditable(false);
        CliFecCesAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliFecCesAnioActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha Ultimo Proyecto");

        CliFecUltDia.setEditable(false);
        CliFecUltDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliFecUltDiaActionPerformed(evt);
            }
        });

        CliFecUltMes.setEditable(false);
        CliFecUltMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliFecUltMesActionPerformed(evt);
            }
        });

        CliFecUltAnio.setEditable(false);
        CliFecUltAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliFecUltAnioActionPerformed(evt);
            }
        });

        jLabel10.setText("Estado Cliente");

        CliEstCli.setEditable(false);
        CliEstCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliEstCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CliFecUltDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CliFecUltMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CliFecUltAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CliFecCesDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CliFecCesMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CliFecCesAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CliFecIngDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CliFecIngMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CliTipCli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CliFecIngAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(533, 533, 533))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CliNom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CliEstReg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CliCod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CliEstCli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(460, 460, 460))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CliCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CliNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CliTipCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CliFecIngAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CliFecIngDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CliFecIngMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CliFecCesDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CliFecCesMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CliFecCesAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CliFecUltDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CliFecUltMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CliFecUltAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CliEstCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CliEstReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("BASE DE DATOS"));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Tipo", "I_Año", "I_Mes", "I_Día", "C_Año", "C_Mes", "C_Dia", "U_Año", "U_Mes", "U_Día", "Estado", "Registro"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("OPCIONES"));

        AgregarBoton.setText("Adicionar");
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });

        ModificarBoton.setText("Modificar");
        ModificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBotonActionPerformed(evt);
            }
        });

        EliminarBoton.setText("Eliminar");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });

        CancelarBoton.setText("Cancelar");
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });

        InactivarBoton.setText("Inactivar");
        InactivarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InactivarBotonActionPerformed(evt);
            }
        });

        ReactivarBoton.setText("Reactivar");
        ReactivarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReactivarBotonActionPerformed(evt);
            }
        });

        ActualizarBoton.setText("Actualizar");
        ActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBotonActionPerformed(evt);
            }
        });

        SalirBoton.setText("Salir");
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InactivarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ModificarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(ReactivarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EliminarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CancelarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(SalirBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarBoton)
                    .addComponent(ModificarBoton)
                    .addComponent(EliminarBoton)
                    .addComponent(CancelarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InactivarBoton)
                    .addComponent(ReactivarBoton)
                    .addComponent(ActualizarBoton)
                    .addComponent(SalirBoton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tituloTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTabla.setText("Titulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
        getFila(fila);
    }//GEN-LAST:event_TablaMouseClicked

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed
        // get y llamar a adicionar
        flagBoton = 1;
        agregar();
    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void ModificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 2;
        modificar();
    }//GEN-LAST:event_ModificarBotonActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 3;
        eliminar();
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void InactivarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InactivarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 4;
        inactivar();
    }//GEN-LAST:event_InactivarBotonActionPerformed

    private void ReactivarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReactivarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 5;
        reactivar();
    }//GEN-LAST:event_ReactivarBotonActionPerformed

    private void ActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBotonActionPerformed
        actualizar();
        consulta();
    }//GEN-LAST:event_ActualizarBotonActionPerformed

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed
    
    private final String NOMBRE_TABLA = "c1m_clientes";
    private final String NOMBRE_INSTACIA = "Cliente";
    private final int CANTIDAD_DATOS = 14;
    
    private final String NOMBRE_DATO_1 = "CliCod";
    private final String NOMBRE_DATO_2 = "CliNom";
    private final String NOMBRE_DATO_3 = "CliTipCli";
    private final String NOMBRE_DATO_4 = "CliFecIngAño";
    private final String NOMBRE_DATO_5 = "CliFecIngMes";
    private final String NOMBRE_DATO_6 = "CliFecIngDia";
    private final String NOMBRE_DATO_7 = "CliFecCesAño";
    private final String NOMBRE_DATO_8 = "CliFecCesMes";
    private final String NOMBRE_DATO_9 = "CliFecCesDia";
    private final String NOMBRE_DATO_10 = "CliFecUltProCerAño";
    private final String NOMBRE_DATO_11 = "CliFecUltProCerMes";
    private final String NOMBRE_DATO_12 = "CliFecUltProCerDia";
    private final String NOMBRE_DATO_13 = "CliEstCli";
    private final String NOMBRE_DATO_14 = "CliEstRegCli";
    
    private void CliFecIngDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliFecIngDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliFecIngDiaActionPerformed

    private void CliEstRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliEstRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliEstRegActionPerformed

    private void CliNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliNomActionPerformed

    private void CliTipCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliTipCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliTipCliActionPerformed

    private void CliFecIngMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliFecIngMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliFecIngMesActionPerformed

    private void CliFecIngAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliFecIngAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliFecIngAnioActionPerformed

    private void CliFecCesDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliFecCesDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliFecCesDiaActionPerformed

    private void CliFecCesMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliFecCesMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliFecCesMesActionPerformed

    private void CliFecCesAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliFecCesAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliFecCesAnioActionPerformed

    private void CliFecUltDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliFecUltDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliFecUltDiaActionPerformed

    private void CliFecUltMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliFecUltMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliFecUltMesActionPerformed

    private void CliFecUltAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliFecUltAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliFecUltAnioActionPerformed

    private void CliEstCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliEstCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CliEstCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTable_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTable_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTable_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTable_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTable_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoton;
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JTextField CliCod;
    private javax.swing.JTextField CliEstCli;
    private javax.swing.JTextField CliEstReg;
    private javax.swing.JTextField CliFecCesAnio;
    private javax.swing.JTextField CliFecCesDia;
    private javax.swing.JTextField CliFecCesMes;
    private javax.swing.JTextField CliFecIngAnio;
    private javax.swing.JTextField CliFecIngDia;
    private javax.swing.JTextField CliFecIngMes;
    private javax.swing.JTextField CliFecUltAnio;
    private javax.swing.JTextField CliFecUltDia;
    private javax.swing.JTextField CliFecUltMes;
    private javax.swing.JTextField CliNom;
    private javax.swing.JTextField CliTipCli;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton InactivarBoton;
    private javax.swing.JButton ModificarBoton;
    private javax.swing.JButton ReactivarBoton;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tituloTabla;
    // End of variables declaration//GEN-END:variables

    private void consulta() {
        String sql = "select * from " + NOMBRE_TABLA + " order by " + NOMBRE_DATO_1;

        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] descClientes = new Object[CANTIDAD_DATOS];
            modelo = (DefaultTableModel) Tabla.getModel();
            while (rs.next()) {
                descClientes[0] = rs.getInt(NOMBRE_DATO_1);
                descClientes[1] = rs.getString(NOMBRE_DATO_2);
                descClientes[2] = rs.getInt(NOMBRE_DATO_3);
                descClientes[3] = rs.getInt(NOMBRE_DATO_4);
                descClientes[4] = rs.getInt(NOMBRE_DATO_5);
                descClientes[5] = rs.getInt(NOMBRE_DATO_6);
                descClientes[6] = rs.getInt(NOMBRE_DATO_7);
                descClientes[7] = rs.getInt(NOMBRE_DATO_8);
                descClientes[8] = rs.getInt(NOMBRE_DATO_9);
                descClientes[9] = rs.getInt(NOMBRE_DATO_10);
                descClientes[10] = rs.getInt(NOMBRE_DATO_11);
                descClientes[11] = rs.getInt(NOMBRE_DATO_12);
                descClientes[12] = rs.getInt(NOMBRE_DATO_13);
                descClientes[13] = rs.getString(NOMBRE_DATO_14);
                modelo.addRow(descClientes);
            }
            Tabla.setModel(modelo);

        } catch (Exception e) {
        }
    }

    private void agregar() {
        
        int auto;
        if(modelo.getRowCount() != 0){
            auto = (int) modelo.getValueAt(modelo.getRowCount()-1,0) + 1;
        } else {
            auto = 1;
        }
        
        ActualizarBoton.setEnabled(true);
        CliCod.setText(auto+"");
        CliNom.setEnabled(true);
        CliTipCli.setEnabled(true);
        CliFecIngDia.setEnabled(true);
        CliFecIngMes.setEnabled(true);
        CliFecIngAnio.setEnabled(true);
        CliFecCesDia.setEnabled(true);
        CliFecCesMes.setEnabled(true);
        CliFecCesAnio.setEnabled(true);
        CliFecUltDia.setEnabled(true);
        CliFecUltMes.setEnabled(true);
        CliFecUltAnio.setEnabled(true);
        CliEstCli.setEnabled(true);
        
        CliEstReg.setText("A");
        
        CliCod.setEditable(true);
        CliNom.setEditable(true);
        CliTipCli.setEditable(true);
        CliFecIngDia.setEditable(true);
        CliFecIngMes.setEditable(true);
        CliFecIngAnio.setEditable(true);
        CliFecCesDia.setEditable(true);
        CliFecCesMes.setEditable(true);
        CliFecCesAnio.setEditable(true);
        CliFecUltDia.setEditable(true);
        CliFecUltMes.setEditable(true);
        CliFecUltAnio.setEditable(true);
        CliEstCli.setEditable(true);
        carFlaAct = 1;
        
    }

    private void actualizar() {
        String codigo = CliCod.getText();
        String nombre = CliNom.getText();
        String tipo = CliTipCli.getText();
        String fecIngDia = CliFecIngDia.getText();
        String fecIngMes = CliFecIngMes.getText();
        String fecIngAnio = CliFecIngAnio.getText();
        String fecCesDia = CliFecCesDia.getText();
        String fecCesMes = CliFecCesMes.getText();
        String fecCesAnio = CliFecCesAnio.getText();
        String fecUltDia = CliFecUltDia.getText();
        String fecUltMes = CliFecUltMes.getText();
        String fecUltAnio = CliFecUltAnio.getText();
        String estCli = CliEstCli.getText();
        String estado = CliEstReg.getText();
        switch (flagBoton) {
            case 1:
                //AgregarBoton.setEnabled(false);
                if (((codigo.equals("")) || (nombre.equals("")))) {
                    JOptionPane.showMessageDialog(null, "Falta Ingresar Datos!");
                } else {
                    if ((carFlaAct == 1)) {
                        try {
                            String sql = "insert into " + NOMBRE_TABLA + " (" + NOMBRE_DATO_1 + ", " + NOMBRE_DATO_2 + ", " + NOMBRE_DATO_3 + ", " + NOMBRE_DATO_4 
                                    + ", " + NOMBRE_DATO_5 + ", " + NOMBRE_DATO_6 + ", " + NOMBRE_DATO_7 + ", " + NOMBRE_DATO_8 + ", " + NOMBRE_DATO_9 + ", "
                                    + NOMBRE_DATO_10 + ", " + NOMBRE_DATO_11 + ", " + NOMBRE_DATO_12 + ", " + NOMBRE_DATO_13 + ", " + NOMBRE_DATO_14 + ")"
                                    + "values('" + codigo + "','" + nombre + "','" + tipo + "','" + fecIngAnio + "','" + fecIngMes + "','" + fecIngDia
                                    + "','" + fecCesAnio + "','" + fecCesMes + "','" + fecCesDia + "','" + fecUltAnio + "','" + fecUltMes + "','"
                                    + fecUltDia + "','" + estCli + "','" + estado + "')";
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, "Nuevo " + NOMBRE_INSTACIA + " Registrado!");
                            limpiarFormulario();
                            desactivarFormulario();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e);
                        }
                    } else {
                        System.out.println("Flag Error");
                    }
                }
                break;
            case 2:
                //ModificarBoton.setEnabled(false);
                if (((nombre.equals("")))) {
                    JOptionPane.showMessageDialog(null, "Falta Ingresar Nombre!");
                } else {
                    if ((carFlaAct == 1)) {
                        try {
                            String sql = "update " + NOMBRE_TABLA + " set " + NOMBRE_DATO_2 + "='" + nombre + "', " + NOMBRE_DATO_3 + "='" + tipo + "', "
                                        + NOMBRE_DATO_4 + "='" + fecIngAnio + "', " + NOMBRE_DATO_5 + "='" + fecIngMes + "', " + NOMBRE_DATO_6 + "='" + fecIngDia + "', "
                                        + NOMBRE_DATO_7 + "='" + fecCesAnio + "', " + NOMBRE_DATO_8 + "='" + fecCesMes + "', " + NOMBRE_DATO_9 + "='" + fecCesDia + "', "
                                        + NOMBRE_DATO_10 + "='" + fecUltAnio + "', " + NOMBRE_DATO_11 + "='" + fecUltMes + "', " + NOMBRE_DATO_12 + "='" + fecUltDia + "', "
                                        + NOMBRE_DATO_13 + "='" + estCli + "' where " + NOMBRE_DATO_1 + "=" + codigo;
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA + " Actualizado!");
                            limpiarFormulario();
                            desactivarFormulario();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e);
                        }
                    } else {
                        System.out.println("Flag Error");
                    }
                }
                break;
            case 3:
                //EliminarBoton.setEnabled(false);
                if (carFlaAct == 1) {
                    try {
                        String sql = "update " + NOMBRE_TABLA + " set " + NOMBRE_DATO_14 + "='*' where " + NOMBRE_DATO_1 + "=" + codigo;
                        conet = con1.getConnection();
                        st = conet.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA + " Eliminado!");
                        limpiarFormulario();
                        desactivarFormulario();
                        limpiarTabla();
                    } catch (Exception e) {
                        System.out.println("Error SQL: " + e);
                    }
                }
                break;
            case 4:
                //InactivarBoton.setEnabled(false);
                if (carFlaAct == 1) {
                    try {
                        String sql = "update " + NOMBRE_TABLA + " set " + NOMBRE_DATO_14 + "='I' where " + NOMBRE_DATO_1 + "=" + codigo;
                        conet = con1.getConnection();
                        st = conet.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA + " Inactivado!");
                        limpiarFormulario();
                        desactivarFormulario();
                        limpiarTabla();
                    } catch (Exception e) {
                        System.out.println("Error SQL: " + e);
                    }
                }
                break;
            case 5:
                //ReactivarBoton.setEnabled(false);
                if (estado.equals("*") || estado.equals("I")) {
                    if (carFlaAct == 1) {
                        try {
                            String sql = "update " + NOMBRE_TABLA + " set " + NOMBRE_DATO_14 + "='A' where " + NOMBRE_DATO_1 + "=" + codigo;
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA + " Reactivado!");
                            limpiarFormulario();
                            desactivarFormulario();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El estado se encuentra activo");
                }
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se realizo ninguna modificacion");
                break;
        }
        flagBoton = 0;

    }

    private void cancelar() {
        carFlaAct = 0;
        limpiarFormulario();
        desactivarFormulario();
        ActualizarBoton.setEnabled(false);
    }

    private void limpiarTabla() {
        for (int i = 0; i <= Tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    private void limpiarFormulario() {
        String t = "";
        CliCod.setText(t);
        CliNom.setText(t);
        CliTipCli.setText(t);
        CliFecIngDia.setText(t);
        CliFecIngMes.setText(t);
        CliFecIngAnio.setText(t);
        CliFecCesDia.setText(t);
        CliFecCesMes.setText(t);
        CliFecCesAnio.setText(t);
        CliFecUltDia.setText(t);
        CliFecUltMes.setText(t);
        CliFecUltAnio.setText(t);
        CliEstCli.setText(t);
        CliEstReg.setText(t);
    }

    private void desactivarFormulario() {
        CliCod.setEditable(false);
        CliNom.setEditable(false);
        CliTipCli.setEditable(false);
        CliFecIngDia.setEditable(false);
        CliFecIngMes.setEditable(false);
        CliFecIngAnio.setEditable(false);
        CliFecCesDia.setEditable(false);
        CliFecCesMes.setEditable(false);
        CliFecCesAnio.setEditable(false);
        CliFecUltDia.setEditable(false);
        CliFecUltMes.setEditable(false);
        CliFecUltAnio.setEditable(false);
        CliEstCli.setEditable(false);
        CliEstReg.setEditable(false);
    }

    private void eliminar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String nombre = (String) Tabla.getValueAt(fila, 1).toString();
            String tipo = (String) Tabla.getValueAt(fila, 2).toString();
            String ingAnio = (String) Tabla.getValueAt(fila, 3).toString();
            String ingMes = (String) Tabla.getValueAt(fila, 4).toString();
            String ingDia = (String) Tabla.getValueAt(fila, 5).toString();
            String cesAnio = (String) Tabla.getValueAt(fila, 6).toString();
            String cesMes = (String) Tabla.getValueAt(fila, 7).toString();
            String cesDia = (String) Tabla.getValueAt(fila, 8).toString();
            String ultAnio = (String) Tabla.getValueAt(fila, 9).toString();
            String ultMes = (String) Tabla.getValueAt(fila, 10).toString();
            String ultDia = (String) Tabla.getValueAt(fila, 11).toString();
            String estCli = (String) Tabla.getValueAt(fila, 12).toString();
            String estado = (String) Tabla.getValueAt(fila, 13).toString();

            CliCod.setText("" + idc);
            CliCod.setEditable(false);
            CliCod.setEnabled(false);
            CliNom.setText(nombre);
            CliNom.setEditable(false);
            CliNom.setEnabled(false);
            CliTipCli.setText(tipo);
            CliTipCli.setEditable(false);
            CliTipCli.setEnabled(false);
            CliFecIngDia.setText(ingDia);
            CliFecIngDia.setEditable(false);
            CliFecIngDia.setEnabled(false);
            CliFecIngMes.setText(ingMes);
            CliFecIngMes.setEditable(false);
            CliFecIngMes.setEnabled(false);
            CliFecIngAnio.setText(ingAnio);
            CliFecIngAnio.setEditable(false);
            CliFecIngAnio.setEnabled(false);
            CliFecCesDia.setText(cesDia);
            CliFecCesDia.setEditable(false);
            CliFecCesDia.setEnabled(false);
            CliFecCesMes.setText(cesMes);
            CliFecCesMes.setEditable(false);
            CliFecCesMes.setEnabled(false);
            CliFecCesAnio.setText(cesAnio);
            CliFecCesAnio.setEditable(false);
            CliFecCesAnio.setEnabled(false);
            CliFecUltDia.setText(ultDia);
            CliFecUltDia.setEditable(false);
            CliFecUltDia.setEnabled(false);
            CliFecUltMes.setText(ultMes);
            CliFecUltMes.setEditable(false);
            CliFecUltMes.setEnabled(false);
            CliFecUltAnio.setText(ultAnio);
            CliFecUltAnio.setEditable(false);
            CliFecUltAnio.setEnabled(false);
            CliEstCli.setText(estCli);
            CliEstCli.setEditable(false);
            CliEstCli.setEnabled(false);
            CliEstReg.setText(estado);
            CliEstReg.setEditable(false);
            CliEstReg.setEnabled(false);
            carFlaAct = 1;
            
            //String sql = "select * from c1z_tipo_clientes";
        }
    }

    private void modificar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String nombre = (String) Tabla.getValueAt(fila, 1);
            String tipo = Tabla.getValueAt(fila, 2).toString();
            String ingAnio = Tabla.getValueAt(fila, 3).toString();
            String ingMes = Tabla.getValueAt(fila, 4).toString();
            String ingDia = Tabla.getValueAt(fila, 5).toString();
            String cesAnio = Tabla.getValueAt(fila, 6).toString();
            String cesMes = Tabla.getValueAt(fila, 7).toString();
            String cesDia = Tabla.getValueAt(fila, 8).toString();
            String ultAnio = Tabla.getValueAt(fila, 9).toString();
            String ultMes = Tabla.getValueAt(fila, 10).toString();
            String ultDia = Tabla.getValueAt(fila, 11).toString();
            String estCli = Tabla.getValueAt(fila, 12).toString();
            String estado = (String) Tabla.getValueAt(fila, 13);

            CliCod.setText("" + idc);
            CliCod.setEditable(false);
            CliCod.setEnabled(false);
            CliNom.setText(nombre);
            CliNom.setEditable(true);
            CliNom.setEnabled(true);
            CliTipCli.setText(tipo);
            CliTipCli.setEditable(true);
            CliTipCli.setEnabled(true);
            CliFecIngDia.setText(ingDia);
            CliFecIngDia.setEditable(true);
            CliFecIngDia.setEnabled(true);
            CliFecIngMes.setText(ingMes);
            CliFecIngMes.setEditable(true);
            CliFecIngMes.setEnabled(true);
            CliFecIngAnio.setText(ingAnio);
            CliFecIngAnio.setEditable(true);
            CliFecIngAnio.setEnabled(true);
            CliFecCesDia.setText(cesDia);
            CliFecCesDia.setEditable(true);
            CliFecCesDia.setEnabled(true);
            CliFecCesMes.setText(cesMes);
            CliFecCesMes.setEditable(true);
            CliFecCesMes.setEnabled(true);
            CliFecCesAnio.setText(cesAnio);
            CliFecCesAnio.setEditable(true);
            CliFecCesAnio.setEnabled(true);
            CliFecUltDia.setText(ultDia);
            CliFecUltDia.setEditable(true);
            CliFecUltDia.setEnabled(true);
            CliFecUltMes.setText(ultMes);
            CliFecUltMes.setEditable(true);
            CliFecUltMes.setEnabled(true);
            CliFecUltAnio.setText(ultAnio);
            CliFecUltAnio.setEditable(true);
            CliFecUltAnio.setEnabled(true);
            CliEstCli.setText(estCli);
            CliEstCli.setEditable(true);
            CliEstCli.setEnabled(true);
            CliEstReg.setText(estado);
            CliEstReg.setEditable(false);
            CliEstReg.setEnabled(false);
            
            carFlaAct = 1;

        }
    }

    private void inactivar() {
         ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String nombre = (String) Tabla.getValueAt(fila, 1).toString();
            String tipo = (String) Tabla.getValueAt(fila, 2).toString();
            String ingAnio = (String) Tabla.getValueAt(fila, 3).toString();
            String ingMes = (String) Tabla.getValueAt(fila, 4).toString();
            String ingDia = (String) Tabla.getValueAt(fila, 5).toString();
            String cesAnio = (String) Tabla.getValueAt(fila, 6).toString();
            String cesMes = (String) Tabla.getValueAt(fila, 7).toString();
            String cesDia = (String) Tabla.getValueAt(fila, 8).toString();
            String ultAnio = (String) Tabla.getValueAt(fila, 9).toString();
            String ultMes = (String) Tabla.getValueAt(fila, 10).toString();
            String ultDia = (String) Tabla.getValueAt(fila, 11).toString();
            String estCli = (String) Tabla.getValueAt(fila, 12).toString();
            String estado = (String) Tabla.getValueAt(fila, 13).toString();

            CliCod.setText("" + idc);
            CliCod.setEditable(false);
            CliCod.setEnabled(false);
            CliNom.setText(nombre);
            CliNom.setEditable(false);
            CliNom.setEnabled(false);
            CliTipCli.setText(tipo);
            CliTipCli.setEditable(false);
            CliTipCli.setEnabled(false);
            CliFecIngDia.setText(ingDia);
            CliFecIngDia.setEditable(false);
            CliFecIngDia.setEnabled(false);
            CliFecIngMes.setText(ingMes);
            CliFecIngMes.setEditable(false);
            CliFecIngMes.setEnabled(false);
            CliFecIngAnio.setText(ingAnio);
            CliFecIngAnio.setEditable(false);
            CliFecIngAnio.setEnabled(false);
            CliFecCesDia.setText(cesDia);
            CliFecCesDia.setEditable(false);
            CliFecCesDia.setEnabled(false);
            CliFecCesMes.setText(cesMes);
            CliFecCesMes.setEditable(false);
            CliFecCesMes.setEnabled(false);
            CliFecCesAnio.setText(cesAnio);
            CliFecCesAnio.setEditable(false);
            CliFecCesAnio.setEnabled(false);
            CliFecUltDia.setText(ultDia);
            CliFecUltDia.setEditable(false);
            CliFecUltDia.setEnabled(false);
            CliFecUltMes.setText(ultMes);
            CliFecUltMes.setEditable(false);
            CliFecUltMes.setEnabled(false);
            CliFecUltAnio.setText(ultAnio);
            CliFecUltAnio.setEditable(false);
            CliFecUltAnio.setEnabled(false);
            CliEstCli.setText(estCli);
            CliEstCli.setEditable(false);
            CliEstCli.setEnabled(false);
            CliEstReg.setText(estado);
            CliEstReg.setEditable(false);
            CliEstReg.setEnabled(false);
            carFlaAct = 1;
            

            //String sql = "select * from c1z_tipo_clientes";
        }
    }

    private void reactivar() {
         ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String nombre = (String) Tabla.getValueAt(fila, 1).toString();
            String tipo = (String) Tabla.getValueAt(fila, 2).toString();
            String ingAnio = (String) Tabla.getValueAt(fila, 3).toString();
            String ingMes = (String) Tabla.getValueAt(fila, 4).toString();
            String ingDia = (String) Tabla.getValueAt(fila, 5).toString();
            String cesAnio = (String) Tabla.getValueAt(fila, 6).toString();
            String cesMes = (String) Tabla.getValueAt(fila, 7).toString();
            String cesDia = (String) Tabla.getValueAt(fila, 8).toString();
            String ultAnio = (String) Tabla.getValueAt(fila, 9).toString();
            String ultMes = (String) Tabla.getValueAt(fila, 10).toString();
            String ultDia = (String) Tabla.getValueAt(fila, 11).toString();
            String estCli = (String) Tabla.getValueAt(fila, 12).toString();
            String estado = (String) Tabla.getValueAt(fila, 13).toString();

            CliCod.setText("" + idc);
            CliCod.setEditable(false);
            CliCod.setEnabled(false);
            CliNom.setText(nombre);
            CliNom.setEditable(false);
            CliNom.setEnabled(false);
            CliTipCli.setText(tipo);
            CliTipCli.setEditable(false);
            CliTipCli.setEnabled(false);
            CliFecIngDia.setText(ingDia);
            CliFecIngDia.setEditable(false);
            CliFecIngDia.setEnabled(false);
            CliFecIngMes.setText(ingMes);
            CliFecIngMes.setEditable(false);
            CliFecIngMes.setEnabled(false);
            CliFecIngAnio.setText(ingAnio);
            CliFecIngAnio.setEditable(false);
            CliFecIngAnio.setEnabled(false);
            CliFecCesDia.setText(cesDia);
            CliFecCesDia.setEditable(false);
            CliFecCesDia.setEnabled(false);
            CliFecCesMes.setText(cesMes);
            CliFecCesMes.setEditable(false);
            CliFecCesMes.setEnabled(false);
            CliFecCesAnio.setText(cesAnio);
            CliFecCesAnio.setEditable(false);
            CliFecCesAnio.setEnabled(false);
            CliFecUltDia.setText(ultDia);
            CliFecUltDia.setEditable(false);
            CliFecUltDia.setEnabled(false);
            CliFecUltMes.setText(ultMes);
            CliFecUltMes.setEditable(false);
            CliFecUltMes.setEnabled(false);
            CliFecUltAnio.setText(ultAnio);
            CliFecUltAnio.setEditable(false);
            CliFecUltAnio.setEnabled(false);
            CliEstCli.setText(estCli);
            CliEstCli.setEditable(false);
            CliEstCli.setEnabled(false);
            CliEstReg.setText(estado);
            CliEstReg.setEditable(false);
            CliEstReg.setEnabled(false);
            carFlaAct = 1;
            

            //String sql = "select * from c1z_tipo_clientes";
        }
    }

    private int getFila(int fila) {
        return fila;
    }
}
