/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package print;

import config.ConexionOracle;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel Hincho
 */
public class JTable_Actividades_Etapa extends javax.swing.JFrame {

    ConexionOracle con1 = new ConexionOracle();
    Connection conet;
    DefaultTableModel modelo = new DefaultTableModel();
    Statement st;
    ResultSet rs;
    int idc;
    int flagBoton = 0;
    int carFlaAct = 0;
    public JTable_Actividades_Etapa() {
        initComponents();
        tituloTabla.setText("P13001 - CONTROL DE ACTIVIDADES DE ETAPA");
        setLocationRelativeTo(null);
        ActualizarBoton.setEnabled(false);
        consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tituloTabla = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSecuencia = new javax.swing.JTextField();
        txtTiempoEst = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescr = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        AgregarBoton = new javax.swing.JButton();
        ModificarBoton = new javax.swing.JButton();
        EliminarBoton = new javax.swing.JButton();
        CancelarBoton = new javax.swing.JButton();
        InactivarBoton = new javax.swing.JButton();
        ReactivarBoton = new javax.swing.JButton();
        ActualizarBoton = new javax.swing.JButton();
        SalirBoton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTabla.setText("Titulo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS"));

        jLabel2.setText("Codigo");

        txtCode.setEditable(false);
        txtCode.setEnabled(false);
        txtCode.setName(""); // NOI18N

        jLabel3.setText("Nombre");

        txtNombre.setEditable(false);
        txtNombre.setEnabled(false);

        jLabel4.setText("Estado Registro");

        txtEstado.setEditable(false);
        txtEstado.setEnabled(false);

        jLabel1.setText("Secuencia");

        txtSecuencia.setEnabled(false);

        txtTiempoEst.setEnabled(false);

        jLabel5.setText("Tiempo Estandar");

        jLabel6.setText("Descripción");

        jLabel7.setText("Costo");

        txtDescr.setEnabled(false);

        txtCosto.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescr)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTiempoEst, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 176, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTiempoEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("BASE DE DATOS"));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Secuencia", "Nombre", "Tiempo Estandar", "Descripcion", "Costo", "Estado"
            }
        ));
        jScrollPane2.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("OPCIONES"));

        AgregarBoton.setText("Adicionar");
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });

        ModificarBoton.setText("Modificar");
        ModificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBotonActionPerformed(evt);
            }
        });

        EliminarBoton.setText("Eliminar");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });

        CancelarBoton.setText("Cancelar");
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });

        InactivarBoton.setText("Inactivar");
        InactivarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InactivarBotonActionPerformed(evt);
            }
        });

        ReactivarBoton.setText("Reactivar");
        ReactivarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReactivarBotonActionPerformed(evt);
            }
        });

        ActualizarBoton.setText("Actualizar");
        ActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBotonActionPerformed(evt);
            }
        });

        SalirBoton.setText("Salir");
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(AgregarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModificarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SalirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InactivarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ReactivarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ActualizarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarBoton)
                    .addComponent(ModificarBoton)
                    .addComponent(EliminarBoton)
                    .addComponent(InactivarBoton)
                    .addComponent(ReactivarBoton)
                    .addComponent(ActualizarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalirBoton)
                    .addComponent(CancelarBoton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed
        // get y llamar a adicionar
        flagBoton = 1;
        agregar();
    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void ModificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 2;
        modificar();
    }//GEN-LAST:event_ModificarBotonActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 3;
        eliminar();
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void InactivarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InactivarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 4;
        inactivar();
    }//GEN-LAST:event_InactivarBotonActionPerformed

    private void ReactivarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReactivarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 5;
        reactivar();
    }//GEN-LAST:event_ReactivarBotonActionPerformed

    private void ActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBotonActionPerformed
        actualizar();
    }//GEN-LAST:event_ActualizarBotonActionPerformed

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTable_Actividades_Etapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTable_Actividades_Etapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTable_Actividades_Etapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTable_Actividades_Etapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTable_Actividades_Etapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoton;
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton InactivarBoton;
    private javax.swing.JButton ModificarBoton;
    private javax.swing.JButton ReactivarBoton;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel tituloTabla;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescr;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSecuencia;
    private javax.swing.JTextField txtTiempoEst;
    // End of variables declaration//GEN-END:variables
    
    private final String NOMBRE_TABLA = "p1m_actividades_etapa";
    private final String NOMBRE_INSTACIA = "Actividad Etapa";
    private final int CANTIDAD_DATOS = 7;
    
    private final String NOMBRE_DATO_1 = "ActEtaCod";
    private final String NOMBRE_DATO_2 = "ActEtaSec";
    private final String NOMBRE_DATO_3 = "ActEtaNom";
    private final String NOMBRE_DATO_4 = "ActEtaTpoEst";
    private final String NOMBRE_DATO_5 = "ActEtaDes";
    private final String NOMBRE_DATO_6 = "ActEtaCos";
    private final String NOMBRE_DATO_7 = "ActEtaEstReg";
    
    private void consulta() {
        String sql = "select * from " + NOMBRE_TABLA + " order by " + NOMBRE_DATO_1;

        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] tipoClientes = new Object[CANTIDAD_DATOS];
            modelo = (DefaultTableModel) Tabla.getModel();
            
            //INGRESE NOMBRES DATOS TABLA
            while (rs.next()) { 
                tipoClientes[0] = rs.getInt(NOMBRE_DATO_1);
                tipoClientes[1] = rs.getInt(NOMBRE_DATO_2);
                tipoClientes[2] = rs.getString(NOMBRE_DATO_3);
                tipoClientes[3] = rs.getInt(NOMBRE_DATO_4);
                tipoClientes[4] = rs.getString(NOMBRE_DATO_5);
                tipoClientes[5] = rs.getInt(NOMBRE_DATO_6);
                tipoClientes[6] = rs.getString(NOMBRE_DATO_7);
                modelo.addRow(tipoClientes);
            }
            Tabla.setModel(modelo);

        } catch (Exception e) {
        }
    }

    private void agregar() {
        int auto;
        if(modelo.getRowCount() != 0){
            auto = (int) modelo.getValueAt(modelo.getRowCount()-1,0) + 1;
        } else {
            auto = 1;
        }
        ActualizarBoton.setEnabled(true);
        
        //init not default values
        txtSecuencia.setEnabled(true);
        txtNombre.setEnabled(true);
        txtTiempoEst.setEnabled(true);
        txtDescr.setEnabled(true);
        txtCosto.setEnabled(true);
        
        //default values
        txtCode.setText(auto+"");
        txtEstado.setText("A");
        
        //enable edit
        txtSecuencia.setEditable(true);
        txtNombre.setEditable(true);
        txtTiempoEst.setEditable(true);
        txtDescr.setEditable(true);
        txtCosto.setEditable(true);
        
        carFlaAct = 1;
    }

    private void actualizar() {
        String codigo = txtCode.getText();
        String secuencia = txtSecuencia.getText();
        String nombre = txtNombre.getText();
        String tiempo_estandar = txtTiempoEst.getText();
        String descripcion = txtDescr.getText();
        String costo = txtCosto.getText();
        String estado = txtEstado.getText();
        switch (flagBoton) {
            case 1:
                //AgregarBoton.setEnabled(false);
                if (((codigo.equals("")) || (secuencia.equals("")) || (nombre.equals("")) || 
                        (tiempo_estandar.equals("")) || (descripcion.equals("")) || (costo.equals("")))) {
                    JOptionPane.showMessageDialog(null, "Falta Ingresar Datos!");
                } else {
                    if ((carFlaAct == 1)) {
                        try {
                            String sql = "insert into "+NOMBRE_TABLA+" ("+NOMBRE_DATO_1+", "+NOMBRE_DATO_2+", "+NOMBRE_DATO_3+", "
                                                      +NOMBRE_DATO_4+", "+NOMBRE_DATO_5+", "+NOMBRE_DATO_6+", "+NOMBRE_DATO_7+")"
                                                        + " values('" + codigo + "','" + secuencia + "','" + nombre + "','"
                                                        + tiempo_estandar + "','" + descripcion + "','" + costo + "','" + estado + "')";
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, "Nuevo "+NOMBRE_INSTACIA+" Registrado!");
                            limpiarFormulario();
                            desactivarFormularioEdic();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e.getMessage());
                            consulta();
                        }
                    } else {
                        System.out.println("Flag Error");
                    }
                }
                break;
            case 2:
                //ModificarBoton.setEnabled(false);
                if ((secuencia.equals("")) || (nombre.equals("")) || (tiempo_estandar.equals("")) 
                        || (descripcion.equals("")) || (costo.equals(""))) {
                    JOptionPane.showMessageDialog(null, "Falta Ingresar Datos!");
                } else {
                    if ((carFlaAct == 1)) {
                        try {
                            String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_2+"='" + secuencia +"', "+NOMBRE_DATO_3+"='" + nombre + "', "
                                                                       +NOMBRE_DATO_4+"='" + tiempo_estandar +"', "+NOMBRE_DATO_5+"='" + descripcion + "', "
                                                                       +NOMBRE_DATO_6+"='" + costo 
                                                                       + "' where "+NOMBRE_DATO_1+"=" + codigo;
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Actualizado!");
                            limpiarFormulario();
                            desactivarFormularioEdic();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e.getMessage());
                            consulta();
                        }
                    } else {
                        System.out.println("Flag Error");
                    }
                }
                break;
            case 3:
                //EliminarBoton.setEnabled(false);
                if (carFlaAct == 1) {
                    try {
                        String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_7+"='*' where "+NOMBRE_DATO_1+"=" + codigo;
                        conet = con1.getConnection();
                        st = conet.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Eliminado!");
                        limpiarFormulario();
                        desactivarFormularioEdic();
                        limpiarTabla();
                    } catch (Exception e) {
                        System.out.println("Error SQL: " + e.getMessage());
                        consulta();
                    }
                }
                break;
            case 4:
                //InactivarBoton.setEnabled(false);
                if (carFlaAct == 1) {
                    try {
                        String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_7+"='I' where "+NOMBRE_DATO_1+"=" + codigo;
                        conet = con1.getConnection();
                        st = conet.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Inactivado!");
                        limpiarFormulario();
                        desactivarFormularioEdic();
                        limpiarTabla();
                    } catch (Exception e) {
                        System.out.println("Error SQL: " + e.getMessage());
                        consulta();
                    }
                }
                break;
            case 5:
                //ReactivarBoton.setEnabled(false);
                if (estado.equals("*") || estado.equals("I")) {
                    if (carFlaAct == 1) {
                        try {
                            String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_7+"='A' where "+NOMBRE_DATO_1+"=" + codigo;
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Reactivado!");
                            limpiarFormulario();
                            desactivarFormularioEdic();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e.getMessage());
                            consulta();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El estado se encuentra activo");
                }
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se realizo ninguna modificacion");
                break;
        }
        flagBoton = 0;
        
    }

    private void cancelar() {
        carFlaAct = 0;
        limpiarFormulario();
        desactivarFormularioEdic();
        ActualizarBoton.setEnabled(false);
    }

    private void limpiarTabla() {
        for (int i = 0; i <= Tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    private void limpiarFormulario() {
        String t = "";
        txtCode.setText(t);
        txtSecuencia.setText(t);
        txtNombre.setText(t);
        txtTiempoEst.setText(t);
        txtDescr.setText(t);
        txtCosto.setText(t);
        txtEstado.setText(t);
    }
    
    private void rellenarFormulario(String c, String s, String n, String t, String d, String ct, String e) {
        txtCode.setText(c);
        txtSecuencia.setText(s);
        txtNombre.setText(n);
        txtTiempoEst.setText(t);
        txtDescr.setText(d);
        txtCosto.setText(ct);
        txtEstado.setText(e);
    }
    
    private void desactivarFormularioEdic() {
        txtCode.setEditable(false);
        txtSecuencia.setEditable(false);
        txtNombre.setEditable(false);
        txtTiempoEst.setEditable(false);
        txtDescr.setEditable(false);
        txtCosto.setEditable(false);
        txtEstado.setEditable(false);
        desactivarFormularioEnab();
    }
    
    private void desactivarFormularioEnab() {
        txtCode.setEnabled(false);
        txtSecuencia.setEnabled(false);
        txtNombre.setEnabled(false);
        txtTiempoEst.setEnabled(false);
        txtDescr.setEnabled(false);
        txtCosto.setEnabled(false);
        txtEstado.setEnabled(false);
    }
    
    private void activarFormulario() {
        txtCode.setEditable(true);
        txtCode.setEnabled(true);
        txtSecuencia.setEditable(true);
        txtSecuencia.setEnabled(true);
        txtNombre.setEditable(true);
        txtNombre.setEnabled(true);
        txtTiempoEst.setEditable(true);
        txtTiempoEst.setEnabled(true);
        txtDescr.setEditable(true);
        txtDescr.setEnabled(true);
        txtCosto.setEditable(true);
        txtCosto.setEnabled(true);
        txtEstado.setEditable(true);
        txtEstado.setEnabled(true);
    }

    private void eliminar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String secuencia = (String) Tabla.getValueAt(fila, 1).toString();
            String nombre = (String) Tabla.getValueAt(fila, 2).toString();
            String tiempoEst = (String) Tabla.getValueAt(fila, 3).toString();
            String descripcion = (String) Tabla.getValueAt(fila, 4).toString();
            String costo = (String) Tabla.getValueAt(fila, 5).toString();
            String estado = (String) Tabla.getValueAt(fila, 6).toString();

            rellenarFormulario("" + idc, secuencia, nombre, tiempoEst, descripcion, costo, estado);
            
            desactivarFormularioEdic();
            carFlaAct = 1;

            //String sql = "select * from c1z_tipo_clientes";
        }
    }

    private void modificar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String secuencia = (String) Tabla.getValueAt(fila, 1).toString();
            String nombre = (String) Tabla.getValueAt(fila, 2).toString();
            String tiempoEst = (String) Tabla.getValueAt(fila, 3).toString();
            String descripcion = (String) Tabla.getValueAt(fila, 4).toString();
            String costo = (String) Tabla.getValueAt(fila, 5).toString();
            String estado = (String) Tabla.getValueAt(fila, 6).toString();
            
            rellenarFormulario("" + idc, secuencia, nombre, tiempoEst, descripcion, costo, estado);
            activarFormulario();
            txtCode.setEditable(false);
            txtCode.setEnabled(false);
            txtEstado.setEditable(false);
            txtEstado.setEnabled(false);
            
            carFlaAct = 1;
        }
    }

    private void inactivar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String secuencia = (String) Tabla.getValueAt(fila, 1).toString();
            String nombre = (String) Tabla.getValueAt(fila, 2).toString();
            String tiempoEst = (String) Tabla.getValueAt(fila, 3).toString();
            String descripcion = (String) Tabla.getValueAt(fila, 4).toString();
            String costo = (String) Tabla.getValueAt(fila, 5).toString();
            String estado = (String) Tabla.getValueAt(fila, 6).toString();
            
            rellenarFormulario("" + idc, secuencia, nombre, tiempoEst, descripcion, costo, estado);
            desactivarFormularioEdic();
            carFlaAct = 1;

        }
    }

    private void reactivar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String secuencia = (String) Tabla.getValueAt(fila, 1).toString();
            String nombre = (String) Tabla.getValueAt(fila, 2).toString();
            String tiempoEst = (String) Tabla.getValueAt(fila, 3).toString();
            String descripcion = (String) Tabla.getValueAt(fila, 4).toString();
            String costo = (String) Tabla.getValueAt(fila, 5).toString();
            String estado = (String) Tabla.getValueAt(fila, 6).toString();
            
            rellenarFormulario("" + idc, secuencia, nombre, tiempoEst, descripcion, costo, estado);
            desactivarFormularioEdic();
            carFlaAct = 1;
        }
    }
}
