/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package print;

import config.ConexionOracle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel Hincho
 */
public class JTable_Personal extends javax.swing.JFrame {

    ConexionOracle con1 = new ConexionOracle();
    Connection conet;
    DefaultTableModel modelo = new DefaultTableModel();
    Statement st;
    ResultSet rs;
    int idc;
    int flagBoton = 0;
    int carFlaAct = 0;

    public JTable_Personal() {
        initComponents();
        tituloTabla.setText("R13001 - CONTROL DE PERSONAL");
        setLocationRelativeTo(null);
        ActualizarBoton.setEnabled(false);
        consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PerCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PerNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PerEstRegPer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PerFecIngDia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PerCarCod = new javax.swing.JTextField();
        PerFecIngMes = new javax.swing.JTextField();
        PerFecIngAnio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PerNivExp = new javax.swing.JTextField();
        PerEstOcuCod = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        AgregarBoton = new javax.swing.JButton();
        ModificarBoton = new javax.swing.JButton();
        EliminarBoton = new javax.swing.JButton();
        CancelarBoton = new javax.swing.JButton();
        InactivarBoton = new javax.swing.JButton();
        ReactivarBoton = new javax.swing.JButton();
        ActualizarBoton = new javax.swing.JButton();
        SalirBoton = new javax.swing.JButton();
        tituloTabla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS"));

        jLabel2.setText("Codigo");

        PerCod.setEditable(false);
        PerCod.setName(""); // NOI18N

        jLabel3.setText("Nombre");

        PerNom.setEditable(false);
        PerNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerNomActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado Registro");

        PerEstRegPer.setEditable(false);
        PerEstRegPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerEstRegPerActionPerformed(evt);
            }
        });

        jLabel6.setText("Cargo");

        PerFecIngDia.setEditable(false);
        PerFecIngDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerFecIngDiaActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha Ingreso");

        PerCarCod.setEditable(false);
        PerCarCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerCarCodActionPerformed(evt);
            }
        });

        PerFecIngMes.setEditable(false);
        PerFecIngMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerFecIngMesActionPerformed(evt);
            }
        });

        PerFecIngAnio.setEditable(false);
        PerFecIngAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerFecIngAnioActionPerformed(evt);
            }
        });

        jLabel8.setText("Nivel Experiencia");

        jLabel9.setText("Estado Ocupación");

        PerNivExp.setEditable(false);

        PerEstOcuCod.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PerCod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PerNom, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PerEstOcuCod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PerNivExp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(PerFecIngDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(PerFecIngMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(PerFecIngAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PerEstRegPer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PerCarCod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PerCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PerNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerCarCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PerFecIngDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PerFecIngMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PerFecIngAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PerNivExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(PerEstOcuCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PerEstRegPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("BASE DE DATOS"));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cargo", "I_Año", "I_Mes", "I_Dia", "Experiencia", "Ocupacion", "Registro"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("OPCIONES"));

        AgregarBoton.setText("Adicionar");
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });

        ModificarBoton.setText("Modificar");
        ModificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBotonActionPerformed(evt);
            }
        });

        EliminarBoton.setText("Eliminar");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });

        CancelarBoton.setText("Cancelar");
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });

        InactivarBoton.setText("Inactivar");
        InactivarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InactivarBotonActionPerformed(evt);
            }
        });

        ReactivarBoton.setText("Reactivar");
        ReactivarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReactivarBotonActionPerformed(evt);
            }
        });

        ActualizarBoton.setText("Actualizar");
        ActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBotonActionPerformed(evt);
            }
        });

        SalirBoton.setText("Salir");
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InactivarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ModificarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(ReactivarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EliminarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CancelarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(SalirBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarBoton)
                    .addComponent(ModificarBoton)
                    .addComponent(EliminarBoton)
                    .addComponent(CancelarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InactivarBoton)
                    .addComponent(ReactivarBoton)
                    .addComponent(ActualizarBoton)
                    .addComponent(SalirBoton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tituloTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTabla.setText("Titulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
        getFila(fila);
    }//GEN-LAST:event_TablaMouseClicked

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed
        // get y llamar a adicionar
        flagBoton = 1;
        agregar();
    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void ModificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 2;
        modificar();
    }//GEN-LAST:event_ModificarBotonActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 3;
        eliminar();
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void InactivarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InactivarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 4;
        inactivar();
    }//GEN-LAST:event_InactivarBotonActionPerformed

    private void ReactivarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReactivarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 5;
        reactivar();
    }//GEN-LAST:event_ReactivarBotonActionPerformed

    private void ActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBotonActionPerformed
        actualizar();
        consulta();
    }//GEN-LAST:event_ActualizarBotonActionPerformed

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed
    
    private final String NOMBRE_TABLA = "r1m_personal";
    private final String NOMBRE_INSTACIA = "Personal";
    private final int CANTIDAD_DATOS = 9;
    
    private final String NOMBRE_DATO_1 = "PerCod";
    private final String NOMBRE_DATO_2 = "PerNom";
    private final String NOMBRE_DATO_3 = "PerCarCod";
    private final String NOMBRE_DATO_4 = "PerFecIngAño";
    private final String NOMBRE_DATO_5 = "PerFecIngMes";
    private final String NOMBRE_DATO_6 = "PerFecIngDia";
    private final String NOMBRE_DATO_7 = "PerNivExp";
    private final String NOMBRE_DATO_8 = "PerEstOcuCod";
    private final String NOMBRE_DATO_9 = "PerEstRegPer";
    
    private void PerFecIngDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerFecIngDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerFecIngDiaActionPerformed

    private void PerEstRegPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerEstRegPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerEstRegPerActionPerformed

    private void PerNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerNomActionPerformed

    private void PerCarCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerCarCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerCarCodActionPerformed

    private void PerFecIngMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerFecIngMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerFecIngMesActionPerformed

    private void PerFecIngAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerFecIngAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerFecIngAnioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTable_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTable_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTable_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTable_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTable_Personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoton;
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton InactivarBoton;
    private javax.swing.JButton ModificarBoton;
    private javax.swing.JTextField PerCarCod;
    private javax.swing.JTextField PerCod;
    private javax.swing.JTextField PerEstOcuCod;
    private javax.swing.JTextField PerEstRegPer;
    private javax.swing.JTextField PerFecIngAnio;
    private javax.swing.JTextField PerFecIngDia;
    private javax.swing.JTextField PerFecIngMes;
    private javax.swing.JTextField PerNivExp;
    private javax.swing.JTextField PerNom;
    private javax.swing.JButton ReactivarBoton;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tituloTabla;
    // End of variables declaration//GEN-END:variables

    private void consulta() {
        String sql = "select * from "  +NOMBRE_TABLA + " order by " + NOMBRE_DATO_1;

        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] descClientes = new Object[CANTIDAD_DATOS];
            modelo = (DefaultTableModel) Tabla.getModel();
            while (rs.next()) {
                descClientes[0] = rs.getInt(NOMBRE_DATO_1);
                descClientes[1] = rs.getString(NOMBRE_DATO_2);
                descClientes[2] = rs.getInt(NOMBRE_DATO_3);
                descClientes[3] = rs.getInt(NOMBRE_DATO_4);
                descClientes[4] = rs.getInt(NOMBRE_DATO_5);
                descClientes[5] = rs.getInt(NOMBRE_DATO_6);
                descClientes[6] = rs.getInt(NOMBRE_DATO_7);
                descClientes[7] = rs.getInt(NOMBRE_DATO_8);
                descClientes[8] = rs.getString(NOMBRE_DATO_9);
                modelo.addRow(descClientes);
            }
            Tabla.setModel(modelo);

        } catch (Exception e) {
        }
    }

    private void agregar() {
        
        int auto;
        if(modelo.getRowCount() != 0){
            auto = (int) modelo.getValueAt(modelo.getRowCount()-1,0) + 1;
        } else {
            auto = 1;
        }
        
        ActualizarBoton.setEnabled(true);
        PerCod.setText(auto+"");
        PerNom.setEnabled(true);
        PerCarCod.setEnabled(true);
        PerFecIngDia.setEnabled(true);
        PerFecIngMes.setEnabled(true);
        PerFecIngAnio.setEnabled(true);
        PerNivExp.setEnabled(true);
        PerEstOcuCod.setEnabled(true);
        
        PerEstRegPer.setText("A");
        
        PerCod.setEditable(true);
        PerNom.setEditable(true);
        PerCarCod.setEditable(true);
        PerFecIngDia.setEditable(true);
        PerFecIngMes.setEditable(true);
        PerFecIngAnio.setEditable(true);
        PerNivExp.setEditable(true);
        PerEstOcuCod.setEditable(true);
        carFlaAct = 1;
        
    }

    private void actualizar() {
        String codigo = PerCod.getText();
        String nombre = PerNom.getText();
        String cargo = PerCarCod.getText();
        String fecIngDia = PerFecIngDia.getText();
        String fecIngMes = PerFecIngMes.getText();
        String fecIngAnio = PerFecIngAnio.getText();
        String nivExp = PerNivExp.getText();
        String estOcuCod = PerEstOcuCod.getText();
        String estado = PerEstRegPer.getText();
        switch (flagBoton) {
            case 1:
                //AgregarBoton.setEnabled(false);
                if (((codigo.equals("")) || (nombre.equals("")))) {
                    JOptionPane.showMessageDialog(null, "Falta Ingresar Datos!");
                } else {
                    if ((carFlaAct == 1)) {
                        try {
                            String sql = "insert into " + NOMBRE_TABLA + " (" + NOMBRE_DATO_1 + ", " + NOMBRE_DATO_2 + ", " + NOMBRE_DATO_3 + ", " + NOMBRE_DATO_4 
                                    + ", " + NOMBRE_DATO_5 + ", " + NOMBRE_DATO_6 + ", " + NOMBRE_DATO_7 + ", " + NOMBRE_DATO_8 + ", " + NOMBRE_DATO_9 + ") "
                                    + "values('" + codigo + "','" + nombre + "','" + cargo + "','" + fecIngAnio + "','" + fecIngMes + "','" + fecIngDia
                                    + "','" + nivExp + "','" + estOcuCod + "','" + estado + "')";
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, "Nuevo " + NOMBRE_INSTACIA + " Registrado!");
                            limpiarFormulario();
                            desactivarFormulario();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e);
                        }
                    } else {
                        System.out.println("Flag Error");
                    }
                }
                break;
            case 2:
                //ModificarBoton.setEnabled(false);
                if (((nombre.equals("")))) {
                    JOptionPane.showMessageDialog(null, "Falta Ingresar Nombre!");
                } else {
                    if ((carFlaAct == 1)) {
                        try {
                            String sql = "update " + NOMBRE_TABLA + " set " + NOMBRE_DATO_2 + "='" + nombre + "', " + NOMBRE_DATO_3 + "='" + cargo + "', "
                                       + NOMBRE_DATO_4 + "='" + fecIngAnio + "', " + NOMBRE_DATO_5 + "='" + fecIngMes + "', " + NOMBRE_DATO_6 + "='" + fecIngDia
                                       + "', " + NOMBRE_DATO_7 + "='" + nivExp + "', " + NOMBRE_DATO_8 + "='" + estOcuCod + "' where " + NOMBRE_DATO_1 + "=" + codigo;
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA + " Actualizado!");
                            limpiarFormulario();
                            desactivarFormulario();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e);
                        }
                    } else {
                        System.out.println("Flag Error");
                    }
                }
                break;
            case 3:
                //EliminarBoton.setEnabled(false);
                if (carFlaAct == 1) {
                    try {
                        String sql = "update " + NOMBRE_TABLA + " set " + NOMBRE_DATO_9 + "='*' where " + NOMBRE_DATO_1 + "=" + codigo;
                        conet = con1.getConnection();
                        st = conet.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA + " Eliminado!");
                        limpiarFormulario();
                        desactivarFormulario();
                        limpiarTabla();
                    } catch (Exception e) {
                        System.out.println("Error SQL: " + e);
                    }
                }
                break;
            case 4:
                //InactivarBoton.setEnabled(false);
                if (carFlaAct == 1) {
                    try {
                        String sql = "update " + NOMBRE_TABLA + " set " + NOMBRE_DATO_9 + "='I' where " + NOMBRE_DATO_1 + "=" + codigo;
                        conet = con1.getConnection();
                        st = conet.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA + " Inactivado!");
                        limpiarFormulario();
                        desactivarFormulario();
                        limpiarTabla();
                    } catch (Exception e) {
                        System.out.println("Error SQL: " + e);
                    }
                }
                break;
            case 5:
                //ReactivarBoton.setEnabled(false);
                if (estado.equals("*") || estado.equals("I")) {
                    if (carFlaAct == 1) {
                        try {
                            String sql = "update " + NOMBRE_TABLA + " set " + NOMBRE_DATO_9 + "='A' where " + NOMBRE_DATO_1 + "=" + codigo;
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA + " Reactivado!");
                            limpiarFormulario();
                            desactivarFormulario();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El estado se encuentra activo");
                }
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se realizo ninguna modificacion");
                break;
        }
        flagBoton = 0;

    }

    private void cancelar() {
        carFlaAct = 0;
        limpiarFormulario();
        desactivarFormulario();
        ActualizarBoton.setEnabled(false);
    }

    private void limpiarTabla() {
        for (int i = 0; i <= Tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    private void limpiarFormulario() {
        String t = "";
        PerCod.setText(t);
        PerNom.setText(t);
        PerCarCod.setText(t);
        PerFecIngDia.setText(t);
        PerFecIngMes.setText(t);
        PerFecIngAnio.setText(t);
        PerNivExp.setText(t);
        PerEstOcuCod.setText(t);
        PerEstRegPer.setText(t);
    }

    private void desactivarFormulario() {
        PerCod.setEditable(false);
        PerNom.setEditable(false);
        PerCarCod.setEditable(false);
        PerFecIngDia.setEditable(false);
        PerFecIngMes.setEditable(false);
        PerFecIngAnio.setEditable(false);
        PerNivExp.setEditable(false);
        PerEstOcuCod.setEditable(false);
        PerEstRegPer.setEditable(false);
    }

    private void eliminar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String nombre = (String) Tabla.getValueAt(fila, 1).toString();
            String cargo = (String) Tabla.getValueAt(fila, 2).toString();
            String ingAnio = (String) Tabla.getValueAt(fila, 3).toString();
            String ingMes = (String) Tabla.getValueAt(fila, 4).toString();
            String ingDia = (String) Tabla.getValueAt(fila, 5).toString();
            String nivExp = (String) Tabla.getValueAt(fila, 6).toString();
            String estOcuCod = (String) Tabla.getValueAt(fila, 7).toString();
            String estado = (String) Tabla.getValueAt(fila, 8).toString();

            PerCod.setText("" + idc);
            PerCod.setEditable(false);
            PerCod.setEnabled(false);
            PerNom.setText(nombre);
            PerNom.setEditable(false);
            PerNom.setEnabled(false);
            PerCarCod.setText(cargo);
            PerCarCod.setEditable(false);
            PerCarCod.setEnabled(false);
            PerFecIngDia.setText(ingDia);
            PerFecIngDia.setEditable(false);
            PerFecIngDia.setEnabled(false);
            PerFecIngMes.setText(ingMes);
            PerFecIngMes.setEditable(false);
            PerFecIngMes.setEnabled(false);
            PerFecIngAnio.setText(ingAnio);
            PerFecIngAnio.setEditable(false);
            PerFecIngAnio.setEnabled(false);
            PerNivExp.setText(nivExp);
            PerNivExp.setEditable(false);
            PerNivExp.setEnabled(false);
            PerEstOcuCod.setText(estOcuCod);
            PerEstOcuCod.setEditable(false);
            PerEstOcuCod.setEnabled(false);
            PerEstRegPer.setText(estado);
            PerEstRegPer.setEditable(false);
            PerEstRegPer.setEnabled(false);
            carFlaAct = 1;
            
            //String sql = "select * from c1z_tipo_clientes";
        }
    }

    private void modificar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String nombre = (String) Tabla.getValueAt(fila, 1).toString();
            String cargo = (String) Tabla.getValueAt(fila, 2).toString();
            String ingAnio = (String) Tabla.getValueAt(fila, 3).toString();
            String ingMes = (String) Tabla.getValueAt(fila, 4).toString();
            String ingDia = (String) Tabla.getValueAt(fila, 5).toString();
            String nivExp = (String) Tabla.getValueAt(fila, 6).toString();
            String estOcuCod = (String) Tabla.getValueAt(fila, 7).toString();
            String estado = (String) Tabla.getValueAt(fila, 8).toString();

            PerCod.setText("" + idc);
            PerCod.setEditable(false);
            PerCod.setEnabled(false);
            PerNom.setText(nombre);
            PerNom.setEditable(true);
            PerNom.setEnabled(true);
            PerCarCod.setText(cargo);
            PerCarCod.setEditable(true);
            PerCarCod.setEnabled(true);
            PerFecIngDia.setText(ingDia);
            PerFecIngDia.setEditable(true);
            PerFecIngDia.setEnabled(true);
            PerFecIngMes.setText(ingMes);
            PerFecIngMes.setEditable(true);
            PerFecIngMes.setEnabled(true);
            PerFecIngAnio.setText(ingAnio);
            PerFecIngAnio.setEditable(true);
            PerFecIngAnio.setEnabled(true);
            PerNivExp.setText(nivExp);
            PerNivExp.setEditable(true);
            PerNivExp.setEnabled(true);
            PerEstOcuCod.setText(estOcuCod);
            PerEstOcuCod.setEditable(true);
            PerEstOcuCod.setEnabled(true);
            PerEstRegPer.setText(estado);
            PerEstRegPer.setEditable(false);
            PerEstRegPer.setEnabled(false);
            
            carFlaAct = 1;

        }
    }

    private void inactivar() {
         ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String nombre = (String) Tabla.getValueAt(fila, 1).toString();
            String cargo = (String) Tabla.getValueAt(fila, 2).toString();
            String ingAnio = (String) Tabla.getValueAt(fila, 3).toString();
            String ingMes = (String) Tabla.getValueAt(fila, 4).toString();
            String ingDia = (String) Tabla.getValueAt(fila, 5).toString();
            String nivExp = (String) Tabla.getValueAt(fila, 6).toString();
            String estOcuCod = (String) Tabla.getValueAt(fila, 7).toString();
            String estado = (String) Tabla.getValueAt(fila, 8).toString();

            PerCod.setText("" + idc);
            PerCod.setEditable(false);
            PerCod.setEnabled(false);
            PerNom.setText(nombre);
            PerNom.setEditable(false);
            PerNom.setEnabled(false);
            PerCarCod.setText(cargo);
            PerCarCod.setEditable(false);
            PerCarCod.setEnabled(false);
            PerFecIngDia.setText(ingDia);
            PerFecIngDia.setEditable(false);
            PerFecIngDia.setEnabled(false);
            PerFecIngMes.setText(ingMes);
            PerFecIngMes.setEditable(false);
            PerFecIngMes.setEnabled(false);
            PerFecIngAnio.setText(ingAnio);
            PerFecIngAnio.setEditable(false);
            PerFecIngAnio.setEnabled(false);
            PerNivExp.setText(nivExp);
            PerNivExp.setEditable(false);
            PerNivExp.setEnabled(false);
            PerEstOcuCod.setText(estOcuCod);
            PerEstOcuCod.setEditable(false);
            PerEstOcuCod.setEnabled(false);
            PerEstRegPer.setText(estado);
            PerEstRegPer.setEditable(false);
            PerEstRegPer.setEnabled(false);
            carFlaAct = 1;
            
            //String sql = "select * from c1z_tipo_clientes";
        }
    }

    private void reactivar() {
         ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            String nombre = (String) Tabla.getValueAt(fila, 1).toString();
            String cargo = (String) Tabla.getValueAt(fila, 2).toString();
            String ingAnio = (String) Tabla.getValueAt(fila, 3).toString();
            String ingMes = (String) Tabla.getValueAt(fila, 4).toString();
            String ingDia = (String) Tabla.getValueAt(fila, 5).toString();
            String nivExp = (String) Tabla.getValueAt(fila, 6).toString();
            String estOcuCod = (String) Tabla.getValueAt(fila, 7).toString();
            String estado = (String) Tabla.getValueAt(fila, 8).toString();

            PerCod.setText("" + idc);
            PerCod.setEditable(false);
            PerCod.setEnabled(false);
            PerNom.setText(nombre);
            PerNom.setEditable(false);
            PerNom.setEnabled(false);
            PerCarCod.setText(cargo);
            PerCarCod.setEditable(false);
            PerCarCod.setEnabled(false);
            PerFecIngDia.setText(ingDia);
            PerFecIngDia.setEditable(false);
            PerFecIngDia.setEnabled(false);
            PerFecIngMes.setText(ingMes);
            PerFecIngMes.setEditable(false);
            PerFecIngMes.setEnabled(false);
            PerFecIngAnio.setText(ingAnio);
            PerFecIngAnio.setEditable(false);
            PerFecIngAnio.setEnabled(false);
            PerNivExp.setText(nivExp);
            PerNivExp.setEditable(false);
            PerNivExp.setEnabled(false);
            PerEstOcuCod.setText(estOcuCod);
            PerEstOcuCod.setEditable(false);
            PerEstOcuCod.setEnabled(false);
            PerEstRegPer.setText(estado);
            PerEstRegPer.setEditable(false);
            PerEstRegPer.setEnabled(false);
            carFlaAct = 1;
            
            //String sql = "select * from c1z_tipo_clientes";
        }
    }

    private int getFila(int fila) {
        return fila;
    }
}
