/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package print;

import config.ConexionOracle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class JTable_Proyecto_Movimientos extends javax.swing.JFrame {

    /**
     * Creates new form JTable_Proyecto_Movimientos
     */
    ConexionOracle con1 = new ConexionOracle();
    Connection conet;
    DefaultTableModel modelo = new DefaultTableModel();
    Statement st;
    ResultSet rs;
    int idc;
    int flagBoton = 0;
    int carFlaAct = 0;
    public JTable_Proyecto_Movimientos() {
        initComponents();
        tituloTabla.setText("P1M_PROYECTO");
        setLocationRelativeTo(null);
        ActualizarBoton.setEnabled(false);
        consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloTabla = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSecuencia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEtapaProyecto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTipoProyecto = new javax.swing.JTextField();
        txtPersonal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCargoProyecto = new javax.swing.JTextField();
        txtActividadEtapa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFechaRegAño = new javax.swing.JTextField();
        txtTiempoHoras = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtFechaRegMes = new javax.swing.JTextField();
        txtFechaRegDia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTiempoMinutos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        AgregarBoton = new javax.swing.JButton();
        ModificarBoton = new javax.swing.JButton();
        EliminarBoton = new javax.swing.JButton();
        CancelarBoton = new javax.swing.JButton();
        InactivarBoton = new javax.swing.JButton();
        ReactivarBoton = new javax.swing.JButton();
        ActualizarBoton = new javax.swing.JButton();
        SalirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTabla.setText("Titulo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS"));

        jLabel2.setText("Codigo Cliente");

        txtCodigoCliente.setEditable(false);
        txtCodigoCliente.setEnabled(false);
        txtCodigoCliente.setName(""); // NOI18N

        jLabel3.setText("Secuencia");

        txtSecuencia.setEditable(false);
        txtSecuencia.setEnabled(false);

        jLabel4.setText("Etapa Proyecto");

        txtEtapaProyecto.setEditable(false);
        txtEtapaProyecto.setEnabled(false);

        jLabel1.setText("Tipo Proyecto");

        txtTipoProyecto.setEnabled(false);

        txtPersonal.setEnabled(false);

        jLabel5.setText("Personal");

        jLabel6.setText("Cargo Proyecto");

        jLabel7.setText("Actividad Etapa");

        txtCargoProyecto.setEnabled(false);

        txtActividadEtapa.setEnabled(false);

        jLabel8.setText("Fecha Registro");

        jLabel9.setText("Tiempo Trabajado");

        jLabel10.setText("Estado");

        txtFechaRegAño.setEditable(false);
        txtFechaRegAño.setEnabled(false);

        txtTiempoHoras.setEditable(false);
        txtTiempoHoras.setEnabled(false);

        txtEstado.setEditable(false);
        txtEstado.setEnabled(false);

        txtFechaRegMes.setEditable(false);
        txtFechaRegMes.setEnabled(false);

        txtFechaRegDia.setEditable(false);
        txtFechaRegDia.setEnabled(false);

        jLabel11.setText("(Año/Mes/Dia)");

        txtTiempoMinutos.setEditable(false);
        txtTiempoMinutos.setEnabled(false);

        jLabel12.setText("(Horas:Minutos)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtActividadEtapa, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(txtFechaRegAño)
                    .addComponent(txtTiempoHoras)
                    .addComponent(txtEstado)
                    .addComponent(txtCodigoCliente)
                    .addComponent(txtPersonal)
                    .addComponent(txtSecuencia)
                    .addComponent(txtCargoProyecto)
                    .addComponent(txtTipoProyecto)
                    .addComponent(txtEtapaProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaRegMes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTiempoMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFechaRegDia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActividadEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEtapaProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFechaRegAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaRegMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaRegDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTiempoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTiempoMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("BASE DE DATOS"));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Tipo Proyecto", "Secuencia", "Personal", "Cargo Proyecto", "Actividad Etapa", "Etapa Proyecto", "Fecha Registro", "Tiempo Trabajado", "Estado"
            }
        ));
        jScrollPane2.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("OPCIONES"));

        AgregarBoton.setText("Adicionar");
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });

        ModificarBoton.setText("Modificar");
        ModificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBotonActionPerformed(evt);
            }
        });

        EliminarBoton.setText("Eliminar");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });

        CancelarBoton.setText("Cancelar");
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });

        InactivarBoton.setText("Inactivar");
        InactivarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InactivarBotonActionPerformed(evt);
            }
        });

        ReactivarBoton.setText("Reactivar");
        ReactivarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReactivarBotonActionPerformed(evt);
            }
        });

        ActualizarBoton.setText("Actualizar");
        ActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBotonActionPerformed(evt);
            }
        });

        SalirBoton.setText("Salir");
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(AgregarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModificarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SalirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InactivarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ReactivarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ActualizarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarBoton)
                    .addComponent(ModificarBoton)
                    .addComponent(EliminarBoton)
                    .addComponent(InactivarBoton)
                    .addComponent(ReactivarBoton)
                    .addComponent(ActualizarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalirBoton)
                    .addComponent(CancelarBoton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 139, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed
        // get y llamar a adicionar
        flagBoton = 1;
        agregar();
    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void ModificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 2;
        modificar();
    }//GEN-LAST:event_ModificarBotonActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 3;
        eliminar();
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void InactivarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InactivarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 4;
        inactivar();
    }//GEN-LAST:event_InactivarBotonActionPerformed

    private void ReactivarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReactivarBotonActionPerformed
        // TODO add your handling code here:
        flagBoton = 5;
        reactivar();
    }//GEN-LAST:event_ReactivarBotonActionPerformed

    private void ActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBotonActionPerformed
        actualizar();
    }//GEN-LAST:event_ActualizarBotonActionPerformed

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTable_Proyecto_Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTable_Proyecto_Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTable_Proyecto_Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTable_Proyecto_Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTable_Proyecto_Movimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoton;
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton InactivarBoton;
    private javax.swing.JButton ModificarBoton;
    private javax.swing.JButton ReactivarBoton;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tituloTabla;
    private javax.swing.JTextField txtActividadEtapa;
    private javax.swing.JTextField txtCargoProyecto;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEtapaProyecto;
    private javax.swing.JTextField txtFechaRegAño;
    private javax.swing.JTextField txtFechaRegDia;
    private javax.swing.JTextField txtFechaRegMes;
    private javax.swing.JTextField txtPersonal;
    private javax.swing.JTextField txtSecuencia;
    private javax.swing.JTextField txtTiempoHoras;
    private javax.swing.JTextField txtTiempoMinutos;
    private javax.swing.JTextField txtTipoProyecto;
    // End of variables declaration//GEN-END:variables

    private final String NOMBRE_TABLA = "p1t_proyecto_movimientos";
    private final String NOMBRE_INSTACIA = "Proyecto Movimiento";
    private final int CANTIDAD_DATOS = 13;
    
    private final String NOMBRE_DATO_1 = "ProMovCliCod";
    private final String NOMBRE_DATO_2 = "ProMovTipProCod";
    private final String NOMBRE_DATO_3 = "ProMovSecPro";
    private final String NOMBRE_DATO_4 = "ProMovPerCod";
    private final String NOMBRE_DATO_5 = "ProMovCarProCod";
    private final String NOMBRE_DATO_6 = "ProMovActEtaCod";
    
    private final String NOMBRE_DATO_7 = "ProMovEtaProSec";
    
    private final String NOMBRE_DATO_8 = "ProMovFecRegEtaAño";
    private final String NOMBRE_DATO_9 = "ProMovFecRegEtaMes";
    private final String NOMBRE_DATO_10 = "ProMovFecRegEtaDia";
    
    private final String NOMBRE_DATO_11 = "ProMovEtaHrsTra";
    private final String NOMBRE_DATO_12 = "ProMovEtaMinTra";
    
    private final String NOMBRE_DATO_13 = "ProMovEstReg";
    
    private void consulta() {
        String sql = "select * from " + NOMBRE_TABLA + " order by " + NOMBRE_DATO_1;

        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] tipoClientes = new Object[CANTIDAD_DATOS];
            modelo = (DefaultTableModel) Tabla.getModel();
            
            //INGRESE NOMBRES DATOS TABLA
            while (rs.next()) { 
                tipoClientes[0] = rs.getInt(NOMBRE_DATO_1);
                tipoClientes[1] = rs.getInt(NOMBRE_DATO_2);
                tipoClientes[2] = rs.getInt(NOMBRE_DATO_3);
                tipoClientes[3] = rs.getInt(NOMBRE_DATO_4);
                tipoClientes[4] = rs.getInt(NOMBRE_DATO_5);
                tipoClientes[5] = rs.getInt(NOMBRE_DATO_6);
                tipoClientes[6] = rs.getInt(NOMBRE_DATO_7);
                tipoClientes[7] = rs.getInt(NOMBRE_DATO_8)+"/"+rs.getInt(NOMBRE_DATO_9)+"/"+rs.getInt(NOMBRE_DATO_10);
                tipoClientes[8] = rs.getInt(NOMBRE_DATO_11)+":"+rs.getInt(NOMBRE_DATO_12);
                tipoClientes[9] = rs.getString(NOMBRE_DATO_13);
                
                modelo.addRow(tipoClientes);
            }
            Tabla.setModel(modelo);

        } catch (Exception e) {
        }
    }

    private void agregar() {
        ActualizarBoton.setEnabled(true);
        
        //init not default values
        setFormEdit(true);
        setFormEnab(true);
        
        //default values
        txtEstado.setEditable(false);
        txtEstado.setEnabled(false);
        txtEstado.setText("A");
        
        carFlaAct = 1;
    }

    private void actualizar() {
        String codigo = txtCodigoCliente.getText();
        String tipoProyecto = txtTipoProyecto.getText();
        String secuencia = txtSecuencia.getText();
        
        String personal = txtPersonal.getText();
        String cargoProyecto = txtCargoProyecto.getText();
        String actividadEtapa = txtActividadEtapa.getText();
        
        String etapaProyecto = txtEtapaProyecto.getText();
        String fRegA = txtFechaRegAño.getText();
        String fRegM = txtFechaRegMes.getText();
        String fRegD = txtFechaRegDia.getText();
        String tiempoH = txtTiempoHoras.getText();
        String tiempoM = txtTiempoMinutos.getText();
        String estado = txtEstado.getText();
        
        switch (flagBoton) {
            case 1:
                //AgregarBoton.setEnabled(false);
                if ((codigo.equals("")) || (tipoProyecto.equals("")) || (secuencia.equals("")) || (personal.equals("")) || (cargoProyecto.equals(""))
                  || (actividadEtapa.equals("")) || (etapaProyecto.equals("")) || (fRegA.equals("")) || (fRegM.equals("")) || (fRegD.equals(""))
                  || (tiempoH.equals("")) || (tiempoM.equals("")) || (estado.equals("")) ) {
                    JOptionPane.showMessageDialog(null, "Falta Ingresar Datos!");
                } else {
                    if ((carFlaAct == 1)) {
                        try {
                            String sql = "insert into "+NOMBRE_TABLA+" ("+NOMBRE_DATO_1+", "+NOMBRE_DATO_2+", "+NOMBRE_DATO_3+", "
                                                      +NOMBRE_DATO_4+", "+NOMBRE_DATO_5+", "+NOMBRE_DATO_6+", "+NOMBRE_DATO_7+", "
                                                      +NOMBRE_DATO_8+", "+NOMBRE_DATO_9+", "+NOMBRE_DATO_10+", "+NOMBRE_DATO_11+", "
                                                      +NOMBRE_DATO_12+", "+NOMBRE_DATO_13+")"
                                                        + " values('" + codigo + "','" + tipoProyecto + "','" + secuencia + "','"
                                                        + personal + "','" + cargoProyecto + "','" + actividadEtapa + "','" + etapaProyecto + "','" 
                                                        + fRegA + "','" + fRegM + "','" + fRegD + "','" + tiempoH + "','" 
                                                        + tiempoM + "','" + estado + "')";
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, "Nuevo "+NOMBRE_INSTACIA+" Registrado!");
                            limpiarFormulario();
                            desactivarFormularioEdic();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e.getMessage());
                            consulta();
                        }
                    } else {
                        System.out.println("Flag Error");
                    }
                }
                break;
            case 2:
                //ModificarBoton.setEnabled(false);
                if ((codigo.equals("")) || (tipoProyecto.equals("")) || (secuencia.equals("")) || (personal.equals("")) || (cargoProyecto.equals(""))
                  || (actividadEtapa.equals("")) || (etapaProyecto.equals("")) || (fRegA.equals("")) || (fRegM.equals("")) || (fRegD.equals(""))
                  || (tiempoH.equals("")) || (tiempoM.equals("")) || (estado.equals(""))) {
                    JOptionPane.showMessageDialog(null, "Falta Ingresar Datos!");
                } else {
                    if ((carFlaAct == 1)) {
                        try {
                            String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_1+"='" + codigo +"', "+ NOMBRE_DATO_2+"='" + tipoProyecto +"', "
                                                                       +NOMBRE_DATO_3+"='" + secuencia +"', "+ NOMBRE_DATO_4+"='" + personal +"', "+ NOMBRE_DATO_5+"='" + cargoProyecto +"', "
                                                                       +NOMBRE_DATO_6+"='" + actividadEtapa +"', "+ NOMBRE_DATO_7+"='" + etapaProyecto +"', "
                                                                       +NOMBRE_DATO_8+"='" + fRegA +"', "+ NOMBRE_DATO_9+"='" + fRegM +"', "
                                                                       +NOMBRE_DATO_10+"='" + fRegD +"', "+ NOMBRE_DATO_11+"='" + tiempoH +"', "
                                                                       +NOMBRE_DATO_12+"='" + tiempoM
                                                                       + "' where ("+NOMBRE_DATO_1+"='" + codigo +"' AND "+NOMBRE_DATO_2+"='" + tipoProyecto
                                                                                     +"' AND "+NOMBRE_DATO_3+"='" + secuencia +"' AND "+NOMBRE_DATO_4+"='" + personal 
                                                                                     +"' AND "+NOMBRE_DATO_5+"='" + cargoProyecto +"' AND "+NOMBRE_DATO_6+"='" + actividadEtapa
                                                                                     +"' AND "+NOMBRE_DATO_7+"='" + etapaProyecto +"')";
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Actualizado!");
                            limpiarFormulario();
                            desactivarFormularioEdic();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e.getMessage());
                            consulta();
                        }
                    } else {
                        System.out.println("Flag Error");
                    }
                }
                break;
            case 3:
                //EliminarBoton.setEnabled(false);
                if (carFlaAct == 1) {
                    try {
                        String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_13+"='*' where ("+NOMBRE_DATO_1+"='" + codigo +"' AND "+NOMBRE_DATO_2+"='" + tipoProyecto
                                                                                     +"' AND "+NOMBRE_DATO_3+"='" + secuencia +"' AND "+NOMBRE_DATO_4+"='" + personal 
                                                                                     +"' AND "+NOMBRE_DATO_5+"='" + cargoProyecto +"' AND "+NOMBRE_DATO_6+"='" + actividadEtapa
                                                                                     +"' AND "+NOMBRE_DATO_7+"='" + etapaProyecto +"')";
                        conet = con1.getConnection();
                        st = conet.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Eliminado!");
                        limpiarFormulario();
                        desactivarFormularioEdic();
                        limpiarTabla();
                    } catch (Exception e) {
                        System.out.println("Error SQL: " + e.getMessage());
                        consulta();
                    }
                }
                break;
            case 4:
                //InactivarBoton.setEnabled(false);
                if (carFlaAct == 1) {
                    try {
                        String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_13+"='I' where ("+NOMBRE_DATO_1+"='" + codigo +"' AND "+NOMBRE_DATO_2+"='" + tipoProyecto
                                                                                     +"' AND "+NOMBRE_DATO_3+"='" + secuencia +"' AND "+NOMBRE_DATO_4+"='" + personal 
                                                                                     +"' AND "+NOMBRE_DATO_5+"='" + cargoProyecto +"' AND "+NOMBRE_DATO_6+"='" + actividadEtapa
                                                                                     +"' AND "+NOMBRE_DATO_7+"='" + etapaProyecto +"')";
                        conet = con1.getConnection();
                        st = conet.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Inactivado!");
                        limpiarFormulario();
                        desactivarFormularioEdic();
                        limpiarTabla();
                    } catch (Exception e) {
                        System.out.println("Error SQL: " + e.getMessage());
                        consulta();
                    }
                }
                break;
            case 5:
                //ReactivarBoton.setEnabled(false);
                if (estado.equals("*") || estado.equals("I")) {
                    if (carFlaAct == 1) {
                        try {
                            String sql = "update "+NOMBRE_TABLA+" set "+NOMBRE_DATO_13+"='A' where ("+NOMBRE_DATO_1+"='" + codigo +"' AND "+NOMBRE_DATO_2+"='" + tipoProyecto
                                                                                     +"' AND "+NOMBRE_DATO_3+"='" + secuencia +"' AND "+NOMBRE_DATO_4+"='" + personal 
                                                                                     +"' AND "+NOMBRE_DATO_5+"='" + cargoProyecto +"' AND "+NOMBRE_DATO_6+"='" + actividadEtapa
                                                                                     +"' AND "+NOMBRE_DATO_7+"='" + etapaProyecto +"')";
                            conet = con1.getConnection();
                            st = conet.createStatement();
                            st.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null, NOMBRE_INSTACIA+" Reactivado!");
                            limpiarFormulario();
                            desactivarFormularioEdic();
                            limpiarTabla();
                        } catch (Exception e) {
                            System.out.println("Error SQL: " + e.getMessage());
                            consulta();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El estado se encuentra activo");
                }
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se realizo ninguna modificacion");
                break;
        }
        flagBoton = 0;
        
    }

    private void cancelar() {
        carFlaAct = 0;
        limpiarFormulario();
        desactivarFormularioEdic();
        ActualizarBoton.setEnabled(false);
    }

    private void limpiarTabla() {
        for (int i = 0; i <= Tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    private void limpiarFormulario() {
        String t = "";
        txtCodigoCliente.setText(t);
        txtTipoProyecto.setText(t);
        txtSecuencia.setText(t);
        
        txtPersonal.setText(t);
        txtCargoProyecto.setText(t);
        txtActividadEtapa.setText(t);
        
        txtEtapaProyecto.setText(t);
        txtFechaRegAño.setText(t);
        txtFechaRegMes.setText(t);
        txtFechaRegDia.setText(t);
        txtTiempoHoras.setText(t);
        txtTiempoMinutos.setText(t);
        txtEstado.setText(t);
    }
    
    private void rellenarFormulario(String c, String tp, String s, String p, String cp, String ae,
                                    String ps, String rea, String rem, String red, String eth, String etm,
                                    String e) {
        txtCodigoCliente.setText(c);
        txtTipoProyecto.setText(tp);
        txtSecuencia.setText(s);
        
        txtPersonal.setText(p);
        txtCargoProyecto.setText(cp);
        txtActividadEtapa.setText(ae);
        
        txtEtapaProyecto.setText(ps);
        txtFechaRegAño.setText(rea);
        txtFechaRegMes.setText(rem);
        txtFechaRegDia.setText(red);
        txtTiempoHoras.setText(eth);
        txtTiempoMinutos.setText(etm);
        txtEstado.setText(e);
    }
    
    private void setFormEdit(boolean t){
        txtCodigoCliente.setEditable(t);
        txtTipoProyecto.setEditable(t);
        txtSecuencia.setEditable(t);
        
        txtPersonal.setEditable(t);
        txtCargoProyecto.setEditable(t);
        txtActividadEtapa.setEditable(t);
        
        txtEtapaProyecto.setEditable(t);
        txtFechaRegAño.setEditable(t);
        txtFechaRegMes.setEditable(t);
        txtFechaRegDia.setEditable(t);
        txtTiempoHoras.setEditable(t);
        txtTiempoMinutos.setEditable(t);
        txtEstado.setEditable(t);
    }
    
    private void setFormEnab(boolean t){
        txtCodigoCliente.setEnabled(t);
        txtTipoProyecto.setEnabled(t);
        txtSecuencia.setEnabled(t);
        
        txtPersonal.setEnabled(t);
        txtCargoProyecto.setEnabled(t);
        txtActividadEtapa.setEnabled(t);
        
        txtEtapaProyecto.setEnabled(t);
        txtFechaRegAño.setEnabled(t);
        txtFechaRegMes.setEnabled(t);
        txtFechaRegDia.setEnabled(t);
        txtTiempoHoras.setEnabled(t);
        txtTiempoMinutos.setEnabled(t);
        txtEstado.setEnabled(t);
    }
    
    private void desactivarFormularioEdic() {
        setFormEdit(false);
        desactivarFormularioEnab();
    }
    
    private void desactivarFormularioEnab() {
        setFormEnab(false);
    }
    
    private void activarFormulario() {
        setFormEdit(true);
        setFormEnab(true);
    }

    private void eliminar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            String codigo = (String) Tabla.getValueAt(fila, 0).toString();
            String tipoProyecto = (String) Tabla.getValueAt(fila, 1).toString();
            String secuencia = (String) Tabla.getValueAt(fila, 2).toString();

            String personal = (String) Tabla.getValueAt(fila, 3).toString();
            String cargoProyecto = (String) Tabla.getValueAt(fila, 4).toString();
            String actividadEtapa = (String) Tabla.getValueAt(fila, 5).toString();

            String etapaProyecto = (String) Tabla.getValueAt(fila, 6).toString();
            String fReg = (String) Tabla.getValueAt(fila, 7).toString();
            String fRegA = fReg.substring(0, fReg.indexOf("/"));
            String fRegM = fReg.substring(fReg.indexOf("/")+1, fReg.lastIndexOf("/"));
            String fRegD = fReg.substring(fReg.lastIndexOf("/")+1, fReg.length());
            String tiempo = (String) Tabla.getValueAt(fila, 8).toString();
            String tiempoH = tiempo.substring(0, tiempo.indexOf(":"));
            String tiempoM = tiempo.substring(tiempo.lastIndexOf(":")+1, tiempo.length());
            String estado = (String) Tabla.getValueAt(fila, 9).toString();
            
            rellenarFormulario(codigo, tipoProyecto, secuencia, personal, cargoProyecto, actividadEtapa, 
                               etapaProyecto, fRegA, fRegM, fRegD, tiempoH, tiempoM, estado);
            
            desactivarFormularioEdic();
            carFlaAct = 1;

            //String sql = "select * from c1z_tipo_clientes";
        }
    }

    private void modificar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            String codigo = (String) Tabla.getValueAt(fila, 0).toString();
            String tipoProyecto = (String) Tabla.getValueAt(fila, 1).toString();
            String secuencia = (String) Tabla.getValueAt(fila, 2).toString();

            String personal = (String) Tabla.getValueAt(fila, 3).toString();
            String cargoProyecto = (String) Tabla.getValueAt(fila, 4).toString();
            String actividadEtapa = (String) Tabla.getValueAt(fila, 5).toString();

            String etapaProyecto = (String) Tabla.getValueAt(fila, 6).toString();
            String fReg = (String) Tabla.getValueAt(fila, 7).toString();
            String fRegA = fReg.substring(0, fReg.indexOf("/"));
            String fRegM = fReg.substring(fReg.indexOf("/")+1, fReg.lastIndexOf("/"));
            String fRegD = fReg.substring(fReg.lastIndexOf("/")+1, fReg.length());
            String tiempo = (String) Tabla.getValueAt(fila, 8).toString();
            String tiempoH = tiempo.substring(0, tiempo.indexOf(":"));
            String tiempoM = tiempo.substring(tiempo.lastIndexOf(":")+1, tiempo.length());
            String estado = (String) Tabla.getValueAt(fila, 9).toString();
            
            rellenarFormulario(codigo, tipoProyecto, secuencia, personal, cargoProyecto, actividadEtapa, 
                               etapaProyecto, fRegA, fRegM, fRegD, tiempoH, tiempoM, estado);
            
            activarFormulario();
            txtEstado.setEditable(false);
            txtEstado.setEnabled(false);
            
            carFlaAct = 1;
        }
    }

    private void inactivar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            String codigo = (String) Tabla.getValueAt(fila, 0).toString();
            String tipoProyecto = (String) Tabla.getValueAt(fila, 1).toString();
            String secuencia = (String) Tabla.getValueAt(fila, 2).toString();

            String personal = (String) Tabla.getValueAt(fila, 3).toString();
            String cargoProyecto = (String) Tabla.getValueAt(fila, 4).toString();
            String actividadEtapa = (String) Tabla.getValueAt(fila, 5).toString();

            String etapaProyecto = (String) Tabla.getValueAt(fila, 6).toString();
            String fReg = (String) Tabla.getValueAt(fila, 7).toString();
            String fRegA = fReg.substring(0, fReg.indexOf("/"));
            String fRegM = fReg.substring(fReg.indexOf("/")+1, fReg.lastIndexOf("/"));
            String fRegD = fReg.substring(fReg.lastIndexOf("/")+1, fReg.length());
            String tiempo = (String) Tabla.getValueAt(fila, 8).toString();
            String tiempoH = tiempo.substring(0, tiempo.indexOf(":"));
            String tiempoM = tiempo.substring(tiempo.lastIndexOf(":")+1, tiempo.length());
            String estado = (String) Tabla.getValueAt(fila, 9).toString();
            
            rellenarFormulario(codigo, tipoProyecto, secuencia, personal, cargoProyecto, actividadEtapa, 
                               etapaProyecto, fRegA, fRegM, fRegD, tiempoH, tiempoM, estado);
            desactivarFormularioEdic();
            carFlaAct = 1;

        }
    }

    private void reactivar() {
        ActualizarBoton.setEnabled(true);
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
        } else {
            String codigo = (String) Tabla.getValueAt(fila, 0).toString();
            String tipoProyecto = (String) Tabla.getValueAt(fila, 1).toString();
            String secuencia = (String) Tabla.getValueAt(fila, 2).toString();

            String personal = (String) Tabla.getValueAt(fila, 3).toString();
            String cargoProyecto = (String) Tabla.getValueAt(fila, 4).toString();
            String actividadEtapa = (String) Tabla.getValueAt(fila, 5).toString();

            String etapaProyecto = (String) Tabla.getValueAt(fila, 6).toString();
            String fReg = (String) Tabla.getValueAt(fila, 7).toString();
            String fRegA = fReg.substring(0, fReg.indexOf("/"));
            String fRegM = fReg.substring(fReg.indexOf("/")+1, fReg.lastIndexOf("/"));
            String fRegD = fReg.substring(fReg.lastIndexOf("/")+1, fReg.length());
            String tiempo = (String) Tabla.getValueAt(fila, 8).toString();
            String tiempoH = tiempo.substring(0, tiempo.indexOf(":"));
            String tiempoM = tiempo.substring(tiempo.lastIndexOf(":")+1, tiempo.length());
            String estado = (String) Tabla.getValueAt(fila, 9).toString();
            
            rellenarFormulario(codigo, tipoProyecto, secuencia, personal, cargoProyecto, actividadEtapa, 
                               etapaProyecto, fRegA, fRegM, fRegD, tiempoH, tiempoM, estado);
            desactivarFormularioEdic();
            carFlaAct = 1;
        }
    }
}
